# Social media slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

SOCIAL_MEDIA = [
    ("follower", "následovník", "odběratel, sledující", "She gained a thousand followers.", "Získala tisíc sledujících."),
    ("following", "následování", "kdo koho sleduje / počet sledovaných", "Check my following list.", "Mrkni na seznam, koho sleduju."),
    ("like", "líbit se", "lajk, srdíčko", "Drop a like if you enjoyed it.", "Dej lajk, jestli se ti to líbilo."),
    ("share", "sdílet", "sdílení příspěvku", "Thanks for the share!", "Díky za sdílení!"),
    ("post", "příspěvek", "příspěvek", "I'll post a photo later.", "Později dám fotku."),
    ("story", "příběh", "krátký mizící příspěvek", "Did you see my story?", "Viděl jsi moje story?"),
    ("reel", "cívka", "krátké video (Instagram)", "This reel blew up.", "Tahle reels to roztrhla."),
    ("feed", "krmení", "hlavní proud příspěvků", "My feed is full of ads.", "Feed mám plný reklam."),
    ("dm slide", "vklouznutí do zpráv", "napsat někomu do soukromé schránky", "He slid into her DMs.", "Napsal jí do soukromé schránky."),
    ("influencer", "ovlivňovač", "tvůrce s vlivem na publikum", "She's a travel influencer.", "Je cestovatelská influencerka."),
    ("content", "obsah", "obsah, příspěvky", "He makes great content.", "Dělá skvělý obsah."),
    ("creator", "tvůrce", "tvůrce obsahu", "Support your favorite creators.", "Podpoř své oblíbené tvůrce."),
    ("hashtag", "hashtag", "klíčové slovo s mřížkou", "Add a trending hashtag.", "Přidej populární hashtag."),
    ("tag", "štítek", "označit někoho", "Tag a friend who needs this.", "Označ kámoše, který tohle potřebuje."),
    ("mention", "zmínka", "zmínit/označit účet", "Thanks for the mention.", "Díky za zmínku."),
    ("repost", "přeposlání", "znovu sdílet cizí příspěvek", "Can I repost your photo?", "Můžu sdílet tvoji fotku?"),
    ("caption", "popisek", "text pod příspěvkem", "Need a caption for this photo.", "Potřebuju popisek k téhle fotce."),
    ("filter", "filtr", "efekt na fotku/video", "She used a beauty filter.", "Použila zkrášlovací filtr."),
    ("selfie", "selfíčko", "vlastní fotka", "Let's take a selfie.", "Vyfoťme se na selfie."),
    ("trending", "trendující", "právě populární", "This sound is trending.", "Tenhle zvuk teď frčí."),
    ("viral", "virální", "rychle se šířící", "Her video went viral.", "Její video se rozšířilo všude."),
    ("engagement", "zapojení", "míra interakcí (lajky, komentáře)", "Engagement is down this month.", "Tenhle měsíc je nižší zapojení."),
    ("algorithm", "algoritmus", "systém doporučující obsah", "The algorithm loves short clips.", "Algoritmus má rád krátká videa."),
    ("shadowban", "stínový zákaz", "skryté omezení dosahu", "I think I got shadowbanned.", "Asi mi potají snížili dosah."),
    ("clout chaser", "honič vlivu", "kdo se honí za popularitou", "He's such a clout chaser.", "Pořád se honí za popularitou."),
    ("ratio", "poměr", "víc reakcí než lajků", "Your comment got ratioed.", "Tvůj komentář pohořel v reakcích."),
    ("doomscroll", "scrollovat zkázu", "donekonečna scrollovat špatné zprávy", "Stop doomscrolling before bed.", "Před spaním přestaň hltat špatné zprávy."),
    ("ghost follower", "duchový sledující", "neaktivní sledující", "Half my followers are ghost followers.", "Půlka mých sledujících je neaktivní."),
    ("engagement bait", "návnada na interakce", "obsah lákající reakce", "Asking 'agree?' is engagement bait.", "Otázka 'souhlasíš?' je návnada na reakce."),
    ("verified", "ověřený", "ověřený účet s odznakem", "His account is verified.", "Jeho účet je ověřený."),
    ("blue check", "modré zatržítko", "odznak ověření", "She finally got the blue check.", "Konečně dostala ověřovací odznak."),
    ("unfollow", "odsledovat", "přestat sledovat", "I unfollowed that page.", "Tu stránku jsem přestal sledovat."),
    ("block", "blokovat", "zablokovat účet", "I had to block a troll.", "Musel jsem zablokovat trolla."),
    ("mute", "ztlumit", "skrýt obsah bez unfollow", "I muted his stories.", "Ztlumil jsem jeho story."),
    ("notification", "oznámení", "upozornění z aplikace", "Turn on notifications.", "Zapni si oznámení."),
    ("dms", "přímé zprávy", "soukromé zprávy", "Check your DMs.", "Mrkni do soukromých zpráv."),
    ("link in bio", "odkaz v biu", "odkaz v profilu", "Shop now, link in bio.", "Nakupuj, odkaz v profilu."),
    ("swipe up", "přejeď nahoru", "otevřít odkaz tažením", "Swipe up for the recipe.", "Přejeď nahoru pro recept."),
    ("go live", "jít naživo", "spustit živé vysílání", "I'll go live at eight.", "V osm jdu naživo."),
    ("livestream", "živý proud", "živé vysílání", "Join my livestream tonight.", "Připoj se na můj livestream."),
    ("subscriber", "odběratel", "odběratel kanálu", "Thanks to my subscribers!", "Díky mým odběratelům!"),
    ("subscribe", "odebírat", "přihlásit se k odběru", "Like and subscribe!", "Lajkni a odebírej!"),
    ("collab", "kolab", "spolupráce tvůrců", "We're doing a collab.", "Děláme spolupráci."),
    ("shoutout", "zvolání", "veřejné doporučení účtu", "She gave me a shoutout.", "Veřejně mě doporučila."),
    ("dm flood", "záplava zpráv", "spousta soukromých zpráv", "My DMs are a flood today.", "Schránku mám dneska zaplavenou."),
    ("pinned post", "připnutý příspěvek", "příspěvek nahoře profilu", "Read my pinned post.", "Přečti si můj připnutý příspěvek."),
    ("highlight", "zvýraznění", "uložené story na profilu", "It's in my highlights.", "Je to v mých uložených story."),
    ("face reveal", "odhalení obličeje", "první ukázání tváře online", "He finally did a face reveal.", "Konečně ukázal obličej."),
    ("ratio bait", "návnada na poměr", "provokace lákající kritiku", "Don't fall for the ratio bait.", "Neskoč na tu provokaci."),
    ("engagement farming", "farmení interakcí", "uměle tlačit na reakce", "That's just engagement farming.", "To je jen umělé tlačení na reakce."),
    ("dead account", "mrtvý účet", "neaktivní účet", "It's basically a dead account.", "Je to vlastně mrtvý účet."),
    ("burner account", "vyhazovací účet", "anonymní vedlejší účet", "He commented from a burner account.", "Komentoval z anonymního účtu."),
    ("ratio king", "král poměru", "kdo schytává kritiku", "He's the ratio king today.", "Dneska to schytává on."),
    ("clickbait thumbnail", "návnadový náhled", "lákavý klamavý náhled videa", "That clickbait thumbnail is misleading.", "Ten náhled videa je klamavý."),
    ("trend", "trend", "aktuální oblíbený formát", "Everyone's doing this trend.", "Tenhle trend dělají všichni."),
    ("challenge", "výzva", "soutěžní/zábavní úkol", "Did you try the dance challenge?", "Zkoušel jsi tu taneční výzvu?"),
    ("duet", "duet", "video reagující na jiné vedle sebe", "She did a duet with my clip.", "Udělala duet s mým videem."),
    ("stitch", "sešití", "navázání na cizí video", "He stitched my video.", "Navázal na moje video."),
    ("for you page", "stránka pro tebe", "doporučená záložka (FYP)", "I found you on my For You page.", "Našel jsem tě v doporučených."),
    ("fyp", "fyp", "doporučená záložka (for you page)", "This blew up on the fyp.", "Tohle to roztrhlo v doporučených."),
    ("ratio attack", "poměrový útok", "vlna kritiky", "His post survived a ratio attack.", "Jeho příspěvek přežil vlnu kritiky."),
    ("oversharing", "přílišné sdílení", "sdílení příliš osobního", "That's a bit of oversharing.", "To už je trochu moc osobní."),
    ("flop era", "éra propadáků", "období neúspěchu", "He's in his flop era.", "Má teď období propadáků."),
    ("main account", "hlavní účet", "primární profil", "I posted it on my main account.", "Dal jsem to na hlavní účet."),
    ("private account", "soukromý účet", "neveřejný profil", "Her account is private.", "Má soukromý účet."),
    ("public account", "veřejný účet", "veřejný profil", "Make it a public account to grow.", "Pro růst dej účet na veřejný."),
    ("ratio comment", "poměrový komentář", "komentář mířící na kritiku", "Someone left a ratio comment.", "Někdo tam dal provokativní komentář."),
    ("engagement rate", "míra zapojení", "procento interakcí", "Her engagement rate is high.", "Má vysokou míru zapojení."),
    ("dm request", "žádost o zprávu", "zpráva od neznámého", "I got a weird DM request.", "Přišla mi divná žádost o zprávu."),
    ("follow back", "sledovat zpět", "oplatit sledování", "Thanks for the follow, follow back?", "Díky za sledování, oplatíš?"),
    ("ratio loss", "poměrová prohra", "porážka v reakcích", "That was a brutal ratio loss.", "To byla brutální porážka v reakcích."),
    ("dm scam", "podvod ve zprávách", "podvodná soukromá zpráva", "Watch out for DM scams.", "Pozor na podvodné zprávy."),
    ("aesthetic", "estetika", "vizuální styl, ladění", "Her feed has a clean aesthetic.", "Její profil má čistý vizuální styl."),
    ("grid", "mřížka", "uspořádání příspěvků na profilu", "Her grid is perfectly themed.", "Má dokonale sladěný profil."),
    ("throwback", "ohlédnutí zpět", "starší vzpomínková fotka", "Throwback to last summer.", "Vzpomínka na loňské léto."),
    ("tbt", "ohlédnutí ve čtvrtek", "throwback Thursday, retro fotka", "Posting a tbt photo.", "Dávám retro fotku."),
    ("ratio meta", "poměrové meta", "trend hromadné kritiky", "Comments are in ratio meta.", "V komentářích teď frčí kritika."),
    ("dm me", "napiš mi", "napiš mi soukromě", "Interested? DM me.", "Máš zájem? Napiš soukromě."),
    ("ad", "reklama", "placená propagace", "This post is an ad.", "Tenhle příspěvek je reklama."),
    ("sponsored", "sponzorovaný", "placená spolupráce", "It's a sponsored post.", "Je to placený příspěvek."),
    ("paid partnership", "placené partnerství", "placená spolupráce se značkou", "Marked as a paid partnership.", "Označeno jako placená spolupráce."),
    ("ratio battle", "poměrová bitva", "souboj o reakce", "Their replies turned into a ratio battle.", "Z jejich odpovědí byl souboj o reakce."),
    ("save", "uložit", "uložit příspěvek", "Save this for later.", "Ulož si to na později."),
    ("bookmark", "záložka", "uložit do záložek", "Bookmark the tutorial.", "Ulož si ten návod."),
    ("ratio energy", "poměrová energie", "atmosféra blížící se kritiky", "This comment section has ratio energy.", "Tahle diskuze vypadá na kritiku."),
    ("verified badge", "ověřovací odznak", "odznak ověření účtu", "He's chasing the verified badge.", "Honí se za ověřovacím odznakem."),
    ("dm only", "jen soukromě", "řeš to v soukromých zprávách", "Details in DM only.", "Detaily jen v soukromé zprávě."),
    ("ratio club", "klub poměru", "ti, co schytali kritiku", "Another one joins the ratio club.", "Další přibyl do klubu těch, co to schytali."),
    ("creator fund", "fond pro tvůrce", "platforma platí tvůrcům", "She earns from the creator fund.", "Vydělává z fondu pro tvůrce."),
    ("monetize", "zpeněžit", "vydělávat na obsahu", "He monetized his channel.", "Začal vydělávat na svém kanálu."),
    ("ratio storm", "poměrová bouře", "vlna kritiky", "A ratio storm hit his post.", "Jeho příspěvek zasáhla vlna kritiky."),
    ("dm spam", "spam ve zprávách", "spam v soukromé schránce", "Bots are sending DM spam.", "Boti posílají spam do zpráv."),
    ("ratio victory", "poměrové vítězství", "výhra v reakcích", "Clean ratio victory there.", "Pěkné vítězství v reakcích."),
    ("clout", "vliv", "online popularita a vliv", "He did it for clout.", "Udělal to kvůli popularitě."),
    ("ratio confirmed", "poměr potvrzen", "kritika oficiálně vyhrála", "Ratio confirmed, post deleted.", "Schytal to, příspěvek smazán."),
    ("dm leak", "únik zpráv", "zveřejnění soukromých zpráv", "There was a DM leak.", "Unikly soukromé zprávy."),
    ("ratio finisher", "poměrový dokončovač", "komentář, co dorazí kritiku", "That reply was the ratio finisher.", "Ta odpověď to definitivně dorazila."),
    ("personal brand", "osobní značka", "vlastní image online", "She built a strong personal brand.", "Vybudovala si silnou osobní značku."),
]
