# English idioms with literal Czech translation, real meaning, and examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

IDIOMS = [
    ("cool", "chladný", "skvělý, super", "That new car is really cool.", "To nové auto je fakt super."),
    ("what's up", "co je nahoře", "jak se máš / co se děje", "Hey, what's up with you today?", "Ahoj, co se s tebou dneska děje?"),
    ("break a leg", "zlom si nohu", "hodně štěstí", "Break a leg at your audition tonight!", "Hodně štěstí na dnešním konkurzu!"),
    ("piece of cake", "kus dortu", "úplná hračka, snadná věc", "The exam was a piece of cake.", "Ta zkouška byla úplná hračka."),
    ("spill the beans", "vysypat fazole", "prozradit tajemství", "Come on, spill the beans about the party!", "No tak, prozraď to o té oslavě!"),
    ("hit the sack", "praštit do pytle", "jít spát", "I'm exhausted, I'm going to hit the sack.", "Jsem vyčerpaný, jdu spát."),
    ("under the weather", "pod počasím", "cítit se špatně, být nemocný", "I'm feeling a bit under the weather today.", "Dneska se cítím trochu nemocně."),
    ("once in a blue moon", "jednou za modrý měsíc", "velmi zřídka", "We only meet once in a blue moon.", "Potkáváme se jen velmi zřídka."),
    ("cost an arm and a leg", "stát ruku a nohu", "stát majlant", "That watch cost an arm and a leg.", "Ty hodinky stály majlant."),
    ("bite the bullet", "kousnout do kulky", "skousnout to, překonat se", "I'll just bite the bullet and book the dentist.", "Skousnu to a objednám se k zubaři."),
    ("hit the nail on the head", "trefit hřebík do hlavy", "uhodit hřebíček na hlavičku", "You hit the nail on the head with that comment.", "Tím komentářem jsi uhodil hřebíček na hlavičku."),
    ("let the cat out of the bag", "pustit kočku z pytle", "prozradit tajemství", "He let the cat out of the bag about the surprise.", "Prozradil to překvapení."),
    ("the ball is in your court", "míč je na tvé polovině", "teď je řada na tobě", "I've done my part, the ball is in your court now.", "Udělal jsem svoje, teď je řada na tobě."),
    ("beat around the bush", "mlátit kolem keře", "chodit kolem horké kaše", "Stop beating around the bush and tell me.", "Přestaň chodit kolem horké kaše a řekni mi to."),
    ("on the same page", "na stejné stránce", "mít stejný názor / rozumět si", "Let's make sure we're on the same page.", "Ujistěme se, že si rozumíme."),
    ("call it a day", "nazvat to dnem", "skončit s prací pro dnešek", "It's late, let's call it a day.", "Je pozdě, pro dnešek toho necháme."),
    ("cut corners", "řezat rohy", "šetřit na nesprávném místě, odfláknout", "Don't cut corners on safety.", "Nešetři na bezpečnosti."),
    ("get cold feet", "dostat studené nohy", "dostat strach na poslední chvíli", "He got cold feet before the wedding.", "Před svatbou dostal strach."),
    ("hang in there", "viset tam", "vydrž, neztrácej naději", "I know it's hard, just hang in there.", "Vím, že je to těžké, jen vydrž."),
    ("hit the road", "uhodit cestu", "vyrazit na cestu", "It's getting late, we should hit the road.", "Je pozdě, měli bychom vyrazit."),
    ("in hot water", "v horké vodě", "v maléru", "He's in hot water with his boss.", "Má u šéfa pěkný malér."),
    ("keep an eye on", "držet oko na", "dávat pozor na", "Can you keep an eye on my bag?", "Můžeš mi pohlídat tašku?"),
    ("kill two birds with one stone", "zabít dva ptáky jedním kamenem", "zabít dvě mouchy jednou ranou", "By cycling to work I kill two birds with one stone.", "Když jezdím do práce na kole, zabiju dvě mouchy jednou ranou."),
    ("a blessing in disguise", "požehnání v přestrojení", "neštěstí, které se ukáže jako štěstí", "Losing that job was a blessing in disguise.", "Ztráta té práce se nakonec ukázala jako štěstí."),
    ("the last straw", "poslední stéblo", "poslední kapka", "His rude reply was the last straw.", "Jeho drzá odpověď byla poslední kapka."),
    ("speak of the devil", "mluvit o ďáblovi", "my o vlku a vlk za humny", "Speak of the devil, here he comes!", "My o vlku a vlk za humny, už jde!"),
    ("pull someone's leg", "tahat někoho za nohu", "dělat si z někoho legraci", "Relax, I'm just pulling your leg.", "Klid, jenom si z tebe dělám legraci."),
    ("under the table", "pod stolem", "načerno, potají", "They paid him under the table.", "Platili mu načerno."),
    ("a hot potato", "horká brambora", "ožehavé téma", "Immigration is a political hot potato.", "Imigrace je ožehavé politické téma."),
    ("back to the drawing board", "zpět ke kreslicímu prknu", "začít znovu od začátku", "The plan failed, so it's back to the drawing board.", "Plán selhal, takže zpátky na začátek."),
    ("burn the midnight oil", "pálit půlnoční olej", "pracovat dlouho do noci", "She burned the midnight oil to finish the report.", "Pracovala dlouho do noci, aby dodělala report."),
    ("the best of both worlds", "to nejlepší z obou světů", "výhody obou možností najednou", "Working from home gives me the best of both worlds.", "Práce z domova mi dává to nejlepší z obou světů."),
    ("get out of hand", "dostat se z ruky", "vymknout se kontrole", "The party got out of hand.", "Ta party se vymkla kontrole."),
    ("a piece of the action", "kus akce", "podíl na něčem", "Everyone wants a piece of the action.", "Každý chce svůj podíl."),
    ("miss the boat", "zmeškat loď", "promeškat příležitost", "I missed the boat on that investment.", "Tu investiční příležitost jsem promeškal."),
    ("no pain, no gain", "žádná bolest, žádný zisk", "bez práce nejsou koláče", "Training is tough, but no pain, no gain.", "Trénink je tvrdý, ale bez práce nejsou koláče."),
    ("on cloud nine", "na deváté mráčku", "v sedmém nebi", "She's been on cloud nine since the news.", "Od té zprávy je v sedmém nebi."),
    ("once bitten, twice shy", "jednou kousnut, dvakrát plachý", "kdo se spálí, je opatrný", "After that scam he's once bitten, twice shy.", "Po tom podvodu je dvojnásob opatrný."),
    ("the tip of the iceberg", "špička ledovce", "jen špička ledovce", "These complaints are just the tip of the iceberg.", "Tyhle stížnosti jsou jen špička ledovce."),
    ("throw in the towel", "hodit ručník", "vzdát to", "Don't throw in the towel just yet.", "Ještě to nevzdávej."),
    ("when pigs fly", "až prasata budou létat", "až naprší a uschne", "He'll apologize when pigs fly.", "Omluví se, až naprší a uschne."),
    ("a dime a dozen", "deseticent za tucet", "běžné, ničím výjimečné", "Cheap phone cases are a dime a dozen.", "Levné obaly na mobil jsou úplně běžné."),
    ("add fuel to the fire", "přilít palivo do ohně", "přilévat olej do ohně", "Yelling only adds fuel to the fire.", "Křik jen přilévá olej do ohně."),
    ("bend over backwards", "ohýbat se dozadu", "vyjít z kůže, dělat všechno možné", "They bent over backwards to help us.", "Vyšli z kůže, aby nám pomohli."),
    ("by the skin of your teeth", "o kůži svých zubů", "jen tak tak, o vlásek", "We caught the train by the skin of our teeth.", "Stihli jsme vlak jen tak tak."),
    ("cry over spilled milk", "plakat nad rozlitým mlékem", "litovat něčeho, co nelze změnit", "It's done, no use crying over spilled milk.", "Stalo se, nemá cenu nad tím brečet."),
    ("cut to the chase", "přejít k honičce", "jít rovnou k věci", "Let's cut to the chase: what's the price?", "Pojďme rovnou k věci: kolik to stojí?"),
    ("down to earth", "dolů k zemi", "nohama na zemi, skromný", "Despite his fame, he's very down to earth.", "I přes slávu má nohy pevně na zemi."),
    ("face the music", "čelit hudbě", "nést následky", "He has to face the music for his mistake.", "Musí nést následky své chyby."),
    ("get the hang of it", "chytit to za to", "přijít na to, naučit se to", "It's tricky at first, but you'll get the hang of it.", "Zpočátku je to záludné, ale přijdeš na to."),
    ("give the benefit of the doubt", "dát výhodu pochybnosti", "věřit někomu i přes pochyby", "I'll give you the benefit of the doubt this time.", "Tentokrát ti budu věřit."),
    ("go the extra mile", "jít míli navíc", "udělat něco navíc", "Our team always goes the extra mile.", "Náš tým vždycky udělá něco navíc."),
    ("hit the books", "uhodit do knih", "začít se učit", "Exams are coming, time to hit the books.", "Blíží se zkoušky, čas zasednout ke knihám."),
    ("in the same boat", "na stejné lodi", "ve stejné situaci", "We're all in the same boat here.", "Všichni jsme na tom stejně."),
    ("jump on the bandwagon", "naskočit na vůz", "přidat se k většině / módnímu trendu", "Everyone jumped on the bandwagon after the win.", "Po té výhře se přidali úplně všichni."),
    ("keep your chin up", "drž bradu nahoře", "hlavu vzhůru", "Keep your chin up, things will improve.", "Hlavu vzhůru, bude líp."),
    ("let sleeping dogs lie", "nech spící psy ležet", "nešťourat do starých věcí", "Don't bring that up, let sleeping dogs lie.", "Nevytahuj to, nech to plavat."),
    ("make a long story short", "udělat dlouhý příběh krátkým", "abych to zkrátil", "Long story short, we missed the flight.", "Abych to zkrátil, zmeškali jsme let."),
    ("off the top of my head", "z vrcholu mé hlavy", "z hlavy, jen tak zpaměti", "Off the top of my head, I'd say twenty.", "Z hlavy bych řekl dvacet."),
    ("on thin ice", "na tenkém ledě", "na tenkém ledě, riskovat", "You're on thin ice with that attitude.", "S takovým přístupem jsi na tenkém ledě."),
    ("out of the blue", "z modra", "zničehonic", "She called me out of the blue.", "Zničehonic mi zavolala."),
    ("pull yourself together", "dej se dohromady", "vzpamatuj se", "Pull yourself together, we have work to do.", "Vzpamatuj se, máme práci."),
    ("rain on someone's parade", "pršet na něčí průvod", "kazit někomu radost", "I hate to rain on your parade, but it's cancelled.", "Nerad ti kazím radost, ale je to zrušené."),
    ("see eye to eye", "vidět oko na oko", "shodnout se", "We don't always see eye to eye.", "Ne vždycky se shodneme."),
    ("steal someone's thunder", "ukrást něčí hrom", "připsat si cizí zásluhy / zastínit někoho", "Don't steal her thunder at the meeting.", "Nezastiňuj ji na té schůzce."),
    ("take it with a grain of salt", "ber to se zrnkem soli", "ber to s rezervou", "Take online reviews with a grain of salt.", "Recenze na internetu ber s rezervou."),
    ("the whole nine yards", "celých devět yardů", "úplně všechno, do detailu", "They decorated the whole nine yards.", "Vyzdobili to do posledního detailu."),
    ("through thick and thin", "skrz tlusté a tenké", "v dobrém i zlém", "They stayed together through thick and thin.", "Zůstali spolu v dobrém i zlém."),
    ("up in the air", "ve vzduchu", "nejisté, nerozhodnuté", "Our holiday plans are still up in the air.", "Naše prázdninové plány jsou pořád nejisté."),
    ("water under the bridge", "voda pod mostem", "dávno odpuštěná minulost", "That argument is water under the bridge now.", "Ta hádka je dávno minulost."),
    ("wrap your head around", "ovinout hlavu kolem", "pochopit něco složitého", "I can't wrap my head around this math.", "Nemůžu tu matiku pochopit."),
    ("a chip on your shoulder", "tříska na rameni", "mít komplex, být nabroušený", "He's got a chip on his shoulder about school.", "Kvůli škole je pořádně nabroušený."),
    ("bite off more than you can chew", "ukousnout víc, než dokážeš sníst", "naložit si toho moc", "Taking three jobs, he bit off more than he could chew.", "Se třemi prácemi si naložil moc."),
    ("burn bridges", "pálit mosty", "spálit za sebou mosty", "Don't burn bridges when you quit.", "Při odchodu za sebou nepal mosty."),
    ("cross that bridge when you come to it", "překročit ten most, až k němu dojdeš", "řešit problém, až nastane", "We'll cross that bridge when we come to it.", "To budeme řešit, až to nastane."),
    ("every cloud has a silver lining", "každý mrak má stříbrný okraj", "všechno zlé je k něčemu dobré", "Cheer up, every cloud has a silver lining.", "Hlavu vzhůru, všechno zlé je k něčemu dobré."),
    ("get a taste of your own medicine", "ochutnat svůj vlastní lék", "zažít to, co dělá druhým", "He finally got a taste of his own medicine.", "Konečně si zažil to, co dělal ostatním."),
    ("go down in flames", "jít dolů v plamenech", "totálně zkrachovat / pohořet", "The presentation went down in flames.", "Ta prezentace totálně pohořela."),
    ("have a lot on your plate", "mít toho hodně na talíři", "mít plné ruce práce", "I can't help now, I have a lot on my plate.", "Teď nemůžu pomoct, mám plné ruce práce."),
    ("hit rock bottom", "narazit na dno skály", "klesnout na úplné dno", "He hit rock bottom before turning his life around.", "Klesl na úplné dno, než svůj život změnil."),
    ("in the nick of time", "ve špičce času", "na poslední chvíli", "The ambulance arrived in the nick of time.", "Sanitka přijela na poslední chvíli."),
    ("jump the gun", "vystřelit dřív než zazní výstřel", "ukvapit se", "Don't jump the gun, wait for the results.", "Neukvapuj se, počkej na výsledky."),
    ("keep your fingers crossed", "drž zkřížené prsty", "držet palce", "Keep your fingers crossed for me!", "Drž mi palce!"),
    ("a leopard can't change its spots", "leopard nezmění své skvrny", "vlk srst mění, ale ne povahu", "He promised to change, but a leopard can't change its spots.", "Slíbil, že se změní, ale vlk mění srst, ne povahu."),
    ("let bygones be bygones", "nech minulé být minulým", "co bylo, bylo", "Let's let bygones be bygones and move on.", "Co bylo, bylo, pojďme dál."),
    ("make ends meet", "spojit konce", "vyjít s penězi", "It's hard to make ends meet on one salary.", "Z jednoho platu se těžko vyjde."),
    ("not my cup of tea", "není to můj šálek čaje", "není to nic pro mě", "Horror movies are not my cup of tea.", "Horory nejsou nic pro mě."),
    ("on the fence", "na plotě", "nerozhodnutý", "I'm still on the fence about the job offer.", "Pořád jsem nerozhodnutý ohledně té nabídky."),
    ("play it by ear", "hrát to podle ucha", "improvizovat, podle situace", "We have no plan, let's play it by ear.", "Nemáme plán, necháme to na situaci."),
    ("put all your eggs in one basket", "dát všechna vejce do jednoho košíku", "vsadit všechno na jednu kartu", "Don't put all your eggs in one basket.", "Nesázej všechno na jednu kartu."),
    ("read between the lines", "číst mezi řádky", "číst mezi řádky", "Read between the lines of her message.", "Čti mezi řádky její zprávy."),
    ("sit on the fence", "sedět na plotě", "vyhýbat se rozhodnutí", "Politicians often sit on the fence.", "Politici se často vyhýbají rozhodnutí."),
    ("take a rain check", "vzít si poukaz na déšť", "odložit na jindy", "I'll take a rain check on dinner tonight.", "Tu večeři dáme radši jindy."),
    ("the early bird catches the worm", "ranní ptáče chytí červa", "ranní ptáče dál doskáče", "Get up early — the early bird catches the worm.", "Vstávej brzy — ranní ptáče dál doskáče."),
    ("throw caution to the wind", "hodit opatrnost větru", "pustit opatrnost z hlavy", "He threw caution to the wind and quit.", "Pustil opatrnost z hlavy a dal výpověď."),
    ("two peas in a pod", "dva hrášky v lusku", "jako dvojčata, nerozluční", "Those two are like two peas in a pod.", "Ti dva jsou jako jedno tělo."),
    ("under your nose", "pod tvým nosem", "přímo před nosem", "The keys were under your nose the whole time.", "Klíče ti celou dobu byly přímo pod nosem."),
    ("wear your heart on your sleeve", "nosit srdce na rukávu", "dávat city najevo", "She wears her heart on her sleeve.", "Dává city otevřeně najevo."),
    ("a penny for your thoughts", "penny za tvé myšlenky", "na co myslíš?", "You're quiet — a penny for your thoughts?", "Jsi zticha — na co myslíš?"),
    ("actions speak louder than words", "činy mluví hlasitěji než slova", "skutky znamenají víc než slova", "Don't just promise — actions speak louder than words.", "Jen neslibuj — skutky znamenají víc než slova."),
    ("barking up the wrong tree", "štěkat na špatný strom", "hledat chybu na špatném místě", "If you blame me, you're barking up the wrong tree.", "Jestli viníš mě, hledáš na špatném místě."),
    ("the elephant in the room", "slon v místnosti", "zjevný problém, o kterém se mlčí", "Let's address the elephant in the room.", "Pojďme se bavit o tom, o čem se tu mlčí."),
]
