# American slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

AMERICAN_SLANG = [
    ("buck", "samec", "dolar", "It costs five bucks.", "Stojí to pět dolarů."),
    ("bucks", "samci", "dolary", "I spent fifty bucks.", "Utratil jsem padesát dolarů."),
    ("awesome", "úžasné", "super, skvělé", "That concert was awesome.", "Ten koncert byl skvělý."),
    ("dude", "týpek", "kámo, chlape", "Dude, that's insane!", "Kámo, to je šílený!"),
    ("buddy", "kamarádík", "kámoš, kámo", "Thanks, buddy.", "Díky, kámo."),
    ("gonna", "jdoucí na", "budu (going to)", "I'm gonna head out.", "Já vyrazím."),
    ("y'all", "vy všichni", "vy všichni (jižanské)", "How are y'all doing?", "Jak se všichni máte?"),
    ("bummer", "smolař", "smůla, otrava", "No tickets left? Bummer.", "Došly lístky? To je smůla."),
    ("chill", "chladit", "v pohodě, klidný", "He's a chill guy.", "Je to pohodář."),
    ("cool", "chladný", "super, v pohodě", "That's cool with me.", "To je za mě v pohodě."),
    ("legit", "legitimní", "fakt, doopravdy / pravý", "That's legit the best burger.", "To je fakt nejlepší burger."),
    ("totally", "úplně", "naprosto, jasně", "Totally agree with you.", "Naprosto s tebou souhlasím."),
    ("for real", "doopravdy", "vážně, fakt", "Are you for real?", "To myslíš vážně?"),
    ("hang out", "viset venku", "trávit spolu čas", "Wanna hang out later?", "Nechceš se pak sejít?"),
    ("hang", "viset", "pověsit se / pohoda", "Let's just hang tonight.", "Pojďme dneska jen tak pobýt."),
    ("buzzed", "bzučivý", "lehce opilý", "I'm just a little buzzed.", "Jsem jen lehce přiopilý."),
    ("wasted", "zničený", "úplně opilý", "He got totally wasted.", "Úplně se zlil."),
    ("hammered", "zatlučený", "namol opilý", "They were hammered.", "Byli namol."),
    ("grub", "žrádlo", "jídlo", "Let's get some grub.", "Pojďme se najíst."),
    ("chow down", "žvýkat dolů", "pustit se do jídla", "Time to chow down!", "Čas se nacpat!"),
    ("bail", "kauce", "vypařit se, zdrhnout", "He bailed on the plans.", "Vykašlal se na plány."),
    ("flake", "vločka", "nespolehlivý člověk / vykašlat se", "Don't flake on me again.", "Zase mě nevypekni."),
    ("ride", "jízda", "auto, vozítko", "Nice ride, man!", "Pěkná kára, chlape!"),
    ("shotgun", "brokovnice", "místo vedle řidiče", "I call shotgun!", "Já jedu vepředu!"),
    ("crash", "zhroucení", "přespat / zhroutit se spánkem", "Can I crash at your place?", "Můžu u tebe přespat?"),
    ("ditch", "příkop", "ulít se / nechat někoho", "Let's ditch class.", "Pojďme se ulít z hodiny."),
    ("hella", "pekelně", "fakt hodně, strašně", "It's hella hot today.", "Dneska je strašné horko."),
    ("wicked", "ďábelský", "fakt, hodně (zesílení)", "That's wicked cool.", "To je fakt super."),
    ("psyched", "psychnutý", "natěšený, nadšený", "I'm so psyched for the trip.", "Na ten výlet se strašně těším."),
    ("stoked", "rozdmýchaný", "nadšený, natěšený", "I'm stoked about the news.", "Z té zprávy jsem nadšený."),
    ("bummed", "zklamaný", "skleslý, naštvaný", "I'm bummed we can't go.", "Mrzí mě, že nemůžeme jít."),
    ("freaking out", "vyšilování", "panikařit", "Stop freaking out.", "Přestaň panikařit."),
    ("chill out", "vychladnout", "uklidnit se", "Chill out, it's fine.", "Uklidni se, je to v pohodě."),
    ("buck up", "vzmužit nahoru", "vzchopit se", "Buck up, it'll get better.", "Vzchop se, bude líp."),
    ("bucks fast", "dolary rychle", "rychle vydělané peníze", "He made bucks fast online.", "Vydělal rychlé peníze online."),
    ("john hancock", "John Hancock", "podpis", "Put your John Hancock here.", "Připoj sem svůj podpis."),
    ("the boonies", "zapadákov", "zapadlý venkov", "They live out in the boonies.", "Bydlí v úplném zapadákově."),
    ("the sticks", "klacky", "venkovská zapadlina", "We grew up in the sticks.", "Vyrostli jsme na venkovské samotě."),
    ("uptown", "horní město", "lepší část města", "She moved uptown.", "Přestěhovala se do lepší čtvrti."),
    ("downtown", "dolní město", "centrum města", "Let's go downtown.", "Pojďme do centra."),
    ("buck naked", "dolarově nahý", "úplně nahý", "He ran out buck naked.", "Vyběhl úplně nahý."),
    ("ballpark", "hřiště", "hrubý odhad", "Give me a ballpark number.", "Řekni mi hrubý odhad."),
    ("home run", "doběh domů", "úspěch na plné čáře", "The launch was a home run.", "To uvedení byl trefa do černého."),
    ("strike out", "vyautování", "neuspět, prohrát", "I struck out with that job.", "S tou prací jsem pohořel."),
    ("rain check", "déšťová poukázka", "odložení na jindy", "Can I take a rain check?", "Můžeme to dát jindy?"),
    ("touch base", "dotknout se mety", "krátce se spojit", "Let's touch base soon.", "Brzy se spojíme."),
    ("john doe", "John Doe", "neznámá/anonymní osoba", "The report named a John Doe.", "Zpráva uváděla neznámou osobu."),
    ("buck the trend", "vzepřít se trendu", "jít proti proudu", "Their sales bucked the trend.", "Jejich prodeje šly proti proudu."),
    ("knock it off", "srazit to pryč", "nech toho", "Knock it off, you two!", "Nechte toho, vy dva!"),
    ("cut it out", "vyříznout to", "přestaň s tím", "Cut it out, that's not funny.", "Přestaň, to není vtipné."),
    ("my treat", "moje pohoštění", "platím já", "Dinner's on me, my treat.", "Večeři platím já."),
    ("on the house", "na účet domu", "zdarma od podniku", "These drinks are on the house.", "Tyhle drinky jdou na účet podniku."),
    ("a ride or die", "jízda nebo smrt", "věrný kámoš za všech okolností", "She's my ride or die.", "Je to moje věrná kámoška."),
    ("bro", "brácha", "kámo, brácho", "What's up, bro?", "Co je, brácho?"),
    ("homie", "domácí", "kámoš, parťák", "He's my homie from school.", "Je to můj kámoš ze školy."),
    ("squad", "četa", "parta kamarádů", "The whole squad is coming.", "Přijde celá parta."),
    ("crew", "posádka", "parta, partička", "My crew has my back.", "Moje partička mě podrží."),
    ("kicks", "kopance", "tenisky, boty", "Fresh kicks, man!", "Nové tenisky, chlape!"),
    ("threads", "nitě", "oblečení, hadry", "Nice threads tonight.", "Pěkné hadry dneska."),
    ("buck wild", "divoký jako samec", "úplně utržený ze řetězu", "The crowd went buck wild.", "Dav se úplně utrhl ze řetězu."),
    ("amped", "zesílený", "natěšený, nabuzený", "I'm amped for game night.", "Na herní večer jsem nabuzený."),
    ("jonesing", "jonesování", "silně po něčem toužit", "I'm jonesing for coffee.", "Strašně toužím po kávě."),
    ("the munchies", "mlsání", "návaly chuti na jídlo", "I've got the munchies.", "Mám hroznou chuť něco zobat."),
    ("snack", "svačinka", "atraktivní osoba", "He's a total snack.", "Je to fakt fešák."),
    ("sketchy", "načrtnutý", "pochybný, podezřelý", "That alley looks sketchy.", "Ta ulička vypadá podezřele."),
    ("shady", "stinný", "nedůvěryhodný", "He's a shady character.", "Je to pochybná figura."),
    ("janky", "rozvrzaný", "nekvalitní, rozhrkaný", "The app is super janky.", "Ta appka je hrozně rozhrkaná."),
    ("clutch", "spojka", "v klíčový moment skvělý", "That was a clutch play.", "To byla klíčová akce."),
    ("solid", "pevný", "spolehlivý, dobrý", "He did me a solid.", "Prokázal mi laskavost."),
    ("rad", "radikální", "super, parádní", "That trick was rad.", "Ten trik byl parádní."),
    ("gnarly", "sukovitý", "drsný / super (extrémní)", "That wave was gnarly.", "Ta vlna byla brutální."),
    ("epic", "epický", "naprosto úžasný", "That party was epic.", "Ta párty byla úžasná."),
    ("lame", "chromý", "trapný, nudný", "That excuse is lame.", "Ta výmluva je trapná."),
    ("bogus", "falešný", "nepravý, nesmyslný", "That charge is totally bogus.", "Ten poplatek je úplný nesmysl."),
    ("buck the system", "vzepřít se systému", "jít proti systému", "He always bucks the system.", "Vždycky jde proti systému."),
    ("hit me up", "uhoď do mě", "ozvi se mi", "Hit me up this weekend.", "Ozvi se mi o víkendu."),
    ("hang loose", "viset volně", "v klidu, pohoda", "Just hang loose, dude.", "Hlavně klid, kámo."),
    ("score", "skóre", "získat něco skvělého", "I scored free tickets!", "Sehnal jsem lístky zadarmo!"),
    ("busted", "rozbitý", "přistižený / pokažený", "He got busted cheating.", "Načapali ho při podvádění."),
    ("buck fifty", "dolar padesát", "jeden a půl dolaru", "It's just a buck fifty.", "Je to jen dolar padesát."),
    ("dough", "těsto", "peníze, prachy", "He's got serious dough.", "Má pořádné prachy."),
    ("bread", "chleba", "peníze, love", "Gotta make that bread.", "Musím vydělat nějaké love."),
    ("loaded", "naložený", "bohatý, prachatý", "Her family is loaded.", "Její rodina je prachatá."),
    ("broke", "rozbitý", "bez peněz", "I'm broke until payday.", "Do výplaty jsem bez peněz."),
    ("john law", "John zákon", "policie (slang)", "Watch out, John Law's around.", "Pozor, je tu policie."),
    ("the fuzz", "chmýří", "policie (slang)", "The fuzz showed up fast.", "Policajti dorazili rychle."),
    ("cop", "chňapnout", "polda, policista", "A cop pulled us over.", "Zastavil nás policista."),
    ("rookie", "nováček", "začátečník, nováček", "He's a rookie cop.", "Je to policista nováček."),
    ("veteran", "veterán", "ostřílený zkušený člověk", "She's a veteran teacher.", "Je to ostřílená učitelka."),
    ("buck-toothed", "dolarozubý", "s vyčnívajícími zuby", "The cartoon rabbit is buck-toothed.", "Ten kreslený králík má vyčnívající zuby."),
    ("airhead", "vzduchová hlava", "hlupáček, prázdná hlava", "Don't be such an airhead.", "Nebuď takový popleta."),
    ("couch potato", "gaučová brambora", "gaučový povaleč", "He's a total couch potato.", "Je to úplný gaučový povaleč."),
    ("party animal", "párty zvíře", "kdo miluje pařby", "She's a real party animal.", "Je to pořádný pařmen."),
    ("buck stops here", "samec zastaví tady", "odpovědnost je na mně", "The buck stops here with me.", "Odpovědnost nesu já."),
    ("ace", "eso", "skvěle něco zvládnout", "I aced the test.", "Ten test jsem dal na jedničku."),
    ("nail it", "přibít to", "skvěle to zvládnout", "You totally nailed it.", "Naprosto jsi to zvládl."),
    ("bomb", "bomba", "skvělý / úžasný", "That taco was the bomb.", "To taco bylo úžasné."),
    ("blast", "výbuch", "skvělá zábava", "We had a blast.", "Skvěle jsme se bavili."),
    ("buzzkill", "zabiják nálady", "kdo kazí zábavu", "Don't be a buzzkill.", "Nekaz zábavu."),
    ("spill", "rozlít", "vyklopit (informace)", "Come on, spill!", "No tak, vyklop to!"),
    ("buck up buddy", "vzmuž se kamaráde", "vzchop se, kámo", "Buck up, buddy, you got this.", "Vzchop se, kámo, dáš to."),
]
