# English phrasal verbs with literal Czech, real meaning, and examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

PHRASAL_VERBS = [
    ("give up", "dát nahoru", "vzdát se, přestat", "Don't give up on your dream.", "Nevzdávej se svého snu."),
    ("look up", "podívat se nahoru", "vyhledat (informaci)", "Look up the word in a dictionary.", "Vyhledej to slovo ve slovníku."),
    ("turn down", "otočit dolů", "odmítnout / ztlumit", "She turned down the job offer.", "Odmítla tu pracovní nabídku."),
    ("put off", "položit pryč", "odložit, odsunout", "Don't put off your homework.", "Neodkládej úkoly."),
    ("run out of", "vyběhnout z", "dojít (zásoba)", "We ran out of milk.", "Došlo nám mléko."),
    ("come across", "přijít napříč", "narazit na, náhodou najít", "I came across an old photo.", "Náhodou jsem narazil na starou fotku."),
    ("get along", "dostat se podél", "vycházet s někým", "Do you get along with your neighbors?", "Vycházíš se sousedy?"),
    ("bring up", "přinést nahoru", "nadnést téma / vychovat", "She brought up an interesting point.", "Nadnesla zajímavou myšlenku."),
    ("call off", "zavolat pryč", "zrušit", "They called off the wedding.", "Zrušili svatbu."),
    ("carry on", "nést dál", "pokračovat", "Carry on, you're doing great.", "Pokračuj, jde ti to skvěle."),
    ("check out", "zkontrolovat ven", "prohlédnout si / odhlásit se", "Check out this new app.", "Mrkni na tuhle novou appku."),
    ("come up with", "přijít nahoru s", "vymyslet", "She came up with a clever plan.", "Vymyslela chytrý plán."),
    ("figure out", "vyfigurovat ven", "přijít na, vyřešit", "I can't figure out this puzzle.", "Nemůžu tu hádanku rozluštit."),
    ("fill in", "naplnit dovnitř", "vyplnit (formulář) / zastoupit", "Please fill in the form.", "Prosím vyplňte formulář."),
    ("find out", "najít ven", "zjistit", "I need to find out the truth.", "Potřebuju zjistit pravdu."),
    ("get over", "dostat se přes", "překonat, vzpamatovat se", "It took her months to get over the breakup.", "Trvalo jí měsíce se vzpamatovat z rozchodu."),
    ("give back", "dát zpět", "vrátit", "Please give back my book.", "Prosím vrať mi knihu."),
    ("go on", "jít dál", "pokračovat / dít se", "What's going on here?", "Co se to tady děje?"),
    ("hang out", "viset venku", "trávit čas, courat", "We hung out at the mall.", "Courali jsme po nákuďáku."),
    ("hold on", "držet dál", "počkat, vydržet", "Hold on a second, please.", "Vydrž chvilku, prosím."),
    ("look after", "dívat se po", "starat se o", "Can you look after my dog?", "Můžeš se mi postarat o psa?"),
    ("look forward to", "dívat se vpřed k", "těšit se na", "I look forward to seeing you.", "Těším se, až tě uvidím."),
    ("make up", "udělat nahoru", "vymyslet si / usmířit se / nalíčit se", "They made up after the fight.", "Po hádce se usmířili."),
    ("pick up", "zvednout nahoru", "vyzvednout / pochytit", "I'll pick you up at eight.", "Vyzvednu tě v osm."),
    ("point out", "ukázat ven", "upozornit na, poukázat", "She pointed out my mistake.", "Upozornila na mou chybu."),
    ("put up with", "položit nahoru s", "snášet, tolerovat", "I can't put up with the noise.", "Nesnesu ten hluk."),
    ("set up", "nastavit nahoru", "založit, nastavit", "They set up a new company.", "Založili novou firmu."),
    ("show up", "ukázat nahoru", "dostavit se, objevit se", "He didn't show up to the meeting.", "Na schůzku se nedostavil."),
    ("take off", "vzít pryč", "vzlétnout / svléknout / mít úspěch", "The plane took off on time.", "Letadlo vzlétlo včas."),
    ("take over", "vzít přes", "převzít", "She took over the project.", "Převzala ten projekt."),
    ("turn up", "otočit nahoru", "objevit se / zesílit", "He turned up an hour late.", "Objevil se o hodinu později."),
    ("work out", "vypracovat ven", "vyřešit / cvičit / vyjít", "I work out every morning.", "Každé ráno cvičím."),
    ("back up", "zálohovat", "zálohovat / podpořit / couvat", "Always back up your files.", "Vždycky si zálohuj soubory."),
    ("break down", "rozbít dolů", "porouchat se / zhroutit se", "My car broke down on the highway.", "Auto se mi porouchalo na dálnici."),
    ("break up", "rozbít nahoru", "rozejít se", "They broke up last month.", "Minulý měsíc se rozešli."),
    ("bring back", "přinést zpět", "vrátit / připomenout", "This song brings back memories.", "Tahle písnička mi připomíná vzpomínky."),
    ("calm down", "uklidnit dolů", "uklidnit se", "Calm down, everything is fine.", "Uklidni se, všechno je v pořádku."),
    ("catch up", "chytit nahoru", "dohnat / popovídat si", "Let's catch up over coffee.", "Pojďme si popovídat u kávy."),
    ("clean up", "uklidit nahoru", "uklidit", "Clean up your room.", "Ukliď si pokoj."),
    ("come back", "přijít zpět", "vrátit se", "Come back soon!", "Vrať se brzy!"),
    ("come in", "přijít dovnitř", "vejít", "Come in, the door is open.", "Pojď dál, je odemčeno."),
    ("count on", "počítat na", "spolehnout se na", "You can count on me.", "Můžeš se na mě spolehnout."),
    ("cut down on", "řezat dolů na", "omezit (množství)", "I'm cutting down on sugar.", "Omezuju cukr."),
    ("deal with", "jednat s", "vypořádat se s", "I'll deal with it later.", "Vypořádám se s tím později."),
    ("drop off", "upustit pryč", "vysadit / usnout", "I'll drop you off at the station.", "Vysadím tě u nádraží."),
    ("eat out", "jíst venku", "jít na jídlo do restaurace", "Let's eat out tonight.", "Pojďme dneska na jídlo ven."),
    ("end up", "skončit nahoru", "skončit (nakonec)", "We ended up staying home.", "Nakonec jsme zůstali doma."),
    ("get away", "dostat se pryč", "uniknout / utéct", "The thief got away.", "Zloděj utekl."),
    ("get back", "dostat se zpět", "vrátit se / ozvat se", "I'll get back to you tomorrow.", "Ozvu se ti zítra."),
    ("get in", "dostat se dovnitř", "nastoupit / dostat se dovnitř", "Get in the car, we're late.", "Nastup do auta, jdeme pozdě."),
    ("get off", "dostat se pryč", "vystoupit", "Get off at the next stop.", "Vystup na příští zastávce."),
    ("get on", "dostat se na", "nastoupit (do dopravy)", "Get on the bus quickly.", "Rychle nastup do autobusu."),
    ("get up", "dostat se nahoru", "vstát", "I get up at six.", "Vstávám v šest."),
    ("give in", "dát dovnitř", "ustoupit, podlehnout", "Don't give in to pressure.", "Nepodléhej nátlaku."),
    ("go ahead", "jít vpřed", "do toho, pokračuj", "Go ahead, I'm listening.", "Jen do toho, poslouchám."),
    ("go away", "jít pryč", "odejít, zmizet", "Go away, I'm busy.", "Běž pryč, mám práci."),
    ("go back", "jít zpět", "vrátit se", "I never want to go back there.", "Už se tam nikdy nechci vrátit."),
    ("go out", "jít ven", "jít ven / chodit spolu", "We're going out for dinner.", "Jdeme ven na večeři."),
    ("grow up", "růst nahoru", "vyrůst, dospět", "He grew up in Prague.", "Vyrostl v Praze."),
    ("hand in", "podat dovnitř", "odevzdat", "Hand in your essays by Friday.", "Odevzdejte eseje do pátku."),
    ("hand out", "podat ven", "rozdat", "The teacher handed out the tests.", "Učitel rozdal testy."),
    ("hang up", "pověsit nahoru", "zavěsit (telefon)", "She hung up on me.", "Zavěsila mi to."),
    ("head back", "zamířit zpět", "vyrazit zpátky", "It's late, let's head back.", "Je pozdě, pojďme zpátky."),
    ("hold up", "držet nahoru", "zdržet / vydržet", "Sorry to hold you up.", "Promiň, že tě zdržuju."),
    ("keep up", "držet nahoru", "udržet tempo / pokračovat", "I can't keep up with you.", "Nestíhám s tebou držet krok."),
    ("knock out", "vyřadit ven", "knokautovat / vyřadit", "The punch knocked him out.", "Ta rána ho poslala k zemi."),
    ("lay off", "položit pryč", "propustit (z práce)", "The firm laid off staff.", "Firma propustila zaměstnance."),
    ("let down", "nechat dolů", "zklamat", "I won't let you down.", "Nezklamu tě."),
    ("log in", "zalogovat dovnitř", "přihlásit se", "Log in with your email.", "Přihlas se přes e-mail."),
    ("look down on", "dívat se dolů na", "dívat se na někoho spatra", "Don't look down on others.", "Nedívej se na ostatní spatra."),
    ("look into", "dívat se do", "prozkoumat", "We'll look into the problem.", "Ten problém prošetříme."),
    ("look out", "dívat se ven", "dát pozor", "Look out, a car!", "Pozor, auto!"),
    ("move in", "pohnout dovnitř", "nastěhovat se", "They moved in together.", "Nastěhovali se spolu."),
    ("move out", "pohnout ven", "odstěhovat se", "He moved out last week.", "Minulý týden se odstěhoval."),
    ("pass away", "projít pryč", "zemřít", "Her grandfather passed away.", "Její dědeček zemřel."),
    ("pass out", "projít ven", "omdlít", "He passed out from the heat.", "Z vedra omdlel."),
    ("pay back", "zaplatit zpět", "vrátit (peníze)", "I'll pay you back on Friday.", "Vrátím ti to v pátek."),
    ("pick out", "vybrat ven", "vybrat", "Pick out a nice gift.", "Vyber pěkný dárek."),
    ("put away", "položit pryč", "uklidit, dát pryč", "Put away your toys.", "Ukliď si hračky."),
    ("put on", "položit na", "obléct si / zapnout", "Put on your coat.", "Obleč si kabát."),
    ("put out", "položit ven", "uhasit / vystavit", "Firefighters put out the fire.", "Hasiči uhasili oheň."),
    ("run into", "vběhnout do", "potkat náhodou", "I ran into an old friend.", "Náhodou jsem potkal starého kamaráda."),
    ("set off", "nastavit pryč", "vyrazit / spustit", "We set off at dawn.", "Vyrazili jsme za úsvitu."),
    ("settle down", "usadit dolů", "usadit se, zklidnit se", "They settled down in a small town.", "Usadili se v malém městě."),
    ("sign up", "podepsat nahoru", "přihlásit se, zaregistrovat se", "Sign up for the newsletter.", "Zaregistruj se k odběru novinek."),
    ("sort out", "roztřídit ven", "vyřešit, dát do pořádku", "Let's sort out this mess.", "Pojďme dát ten zmatek do pořádku."),
    ("stand out", "stát ven", "vyčnívat, vynikat", "Her work really stands out.", "Její práce opravdu vyniká."),
    ("stay up", "zůstat nahoru", "ponocovat", "We stayed up all night.", "Ponocovali jsme celou noc."),
    ("take after", "vzít po", "být podobný (rodiči)", "She takes after her mother.", "Je celá po mámě."),
    ("take care of", "vzít péči o", "postarat se o", "Take care of yourself.", "Opatruj se."),
    ("throw away", "hodit pryč", "vyhodit", "Don't throw away that bag.", "Tu tašku nevyhazuj."),
    ("try on", "zkusit na", "vyzkoušet si (oblečení)", "Try on these jeans.", "Vyzkoušej si tyhle džíny."),
    ("turn off", "otočit pryč", "vypnout", "Turn off the lights.", "Zhasni světla."),
    ("turn on", "otočit na", "zapnout", "Turn on the TV.", "Zapni televizi."),
    ("turn out", "otočit ven", "dopadnout, ukázat se", "It turned out fine in the end.", "Nakonec to dopadlo dobře."),
    ("use up", "použít nahoru", "spotřebovat", "We used up all the paper.", "Spotřebovali jsme všechen papír."),
    ("wake up", "probudit nahoru", "vzbudit se", "Wake up, it's morning!", "Vzbuď se, je ráno!"),
    ("warm up", "zahřát nahoru", "zahřát se / rozcvičit se", "Warm up before running.", "Před během se rozcvič."),
    ("watch out", "hlídat ven", "dát si pozor", "Watch out for the ice.", "Dej si pozor na led."),
    ("wear out", "nosit ven", "opotřebovat / unavit", "These shoes are worn out.", "Tyhle boty jsou sešlapané."),
    ("work on", "pracovat na", "pracovat na (zlepšení)", "I'm working on my English.", "Pracuju na své angličtině."),
    ("write down", "napsat dolů", "zapsat si", "Write down the address.", "Zapiš si tu adresu."),
]
