# Internet slang and abbreviations with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

INTERNET = [
    ("lol", "lol", "směju se (laughing out loud)", "Lol, that's hilarious.", "Lol, to je k popukání."),
    ("lmao", "lmao", "směju se nahlas (hodně)", "Lmao, I can't stop laughing.", "Nemůžu přestat se smát."),
    ("rofl", "rofl", "válím se smíchy po zemi", "Rofl, that meme got me.", "Válím se, ten meme mě dostal."),
    ("brb", "hned zpět", "hned se vrátím (be right back)", "Brb, getting some water.", "Hned jsem zpět, jdu pro vodu."),
    ("afk", "od klávesnice", "nejsem u počítače (away from keyboard)", "I'll be afk for ten minutes.", "Na deset minut nebudu u počítače."),
    ("imo", "podle mě", "podle mého názoru", "Imo, the first option is better.", "Podle mě je lepší první možnost."),
    ("imho", "podle mého skromného", "podle mého skromného názoru", "Imho, it needs more testing.", "Podle mého skromného názoru to chce víc testů."),
    ("tbh", "abych byl upřímný", "upřímně řečeno (to be honest)", "Tbh, I didn't like it.", "Upřímně, nelíbilo se mi to."),
    ("idk", "nevím", "nevím (I don't know)", "Idk what to choose.", "Nevím, co si vybrat."),
    ("idc", "je mi to jedno", "nezajímá mě to (I don't care)", "Idc what they think.", "Je mi jedno, co si myslí."),
    ("smh", "kroutím hlavou", "kroutím nad tím hlavou (shaking my head)", "He did it again, smh.", "Zase to udělal, kroutím hlavou."),
    ("tldr", "moc dlouhé nečetl jsem", "shrnutí dlouhého textu", "Tldr: the update fixes bugs.", "Ve zkratce: aktualizace opravuje chyby."),
    ("fyi", "pro tvou informaci", "pro tvou informaci", "Fyi, the link expired.", "Pro info, ten odkaz vypršel."),
    ("dm", "přímá zpráva", "soukromá zpráva (direct message)", "Send me a DM.", "Napiš mi do soukromé zprávy."),
    ("op", "původní postující", "autor příspěvku (original poster)", "OP never replied.", "Autor příspěvku se neozval."),
    ("nsfw", "nevhodné do práce", "nevhodné pro práci/veřejnost", "That link is NSFW.", "Ten odkaz není vhodný do práce."),
    ("tbf", "abych byl fér", "abych byl spravedlivý", "Tbf, he warned us.", "Abych byl fér, varoval nás."),
    ("ftw", "pro výhru", "to je nejlepší (for the win)", "Coffee in the morning, ftw.", "Ranní káva, nejlepší věc."),
    ("ama", "zeptej se mě cokoliv", "zeptejte se mě na cokoliv", "I'm a pilot, AMA.", "Jsem pilot, ptejte se na cokoliv."),
    ("eli5", "vysvětli mi jako 5letému", "vysvětli to úplně jednoduše", "Eli5: how do taxes work?", "Vysvětli jednoduše: jak fungují daně?"),
    ("ikr", "já vím, že?", "to mi povídej, viď?", "So expensive! Ikr.", "Tak drahé! Viď, že jo."),
    ("rn", "právě teď", "právě teď (right now)", "I'm busy rn.", "Právě teď mám práci."),
    ("ngl", "nebudu lhát", "po pravdě (not gonna lie)", "Ngl, that's impressive.", "Po pravdě, to je působivé."),
    ("istg", "přísahám bohu", "přísahám (I swear to God)", "Istg if this breaks again...", "Přísahám, jestli se to zase rozbije..."),
    ("fomo", "strach z promeškání", "strach, že o něco přijdu", "I came because of FOMO.", "Přišel jsem ze strachu, že o něco přijdu."),
    ("yolo", "žiješ jen jednou", "žije se jen jednou", "Booked the trip, yolo!", "Zarezervoval jsem zájezd, žije se jen jednou!"),
    ("dms", "přímé zprávy", "soukromá schránka", "My DMs are open.", "Mám otevřenou soukromou schránku."),
    ("meme", "meme", "internetový vtip/obrázek", "This meme is everywhere.", "Tenhle meme je všude."),
    ("troll", "troll", "kdo schválně provokuje online", "Don't feed the troll.", "Nekrm trolla."),
    ("clickbait", "návnada na kliknutí", "lákavý, ale klamavý titulek", "That title is pure clickbait.", "Ten titulek je čistá návnada."),
    ("spam", "spam", "nevyžádané zprávy", "My inbox is full of spam.", "Schránku mám plnou spamu."),
    ("noob", "noob", "začátečník, nezkušený", "I'm a total noob at this.", "V tomhle jsem úplný začátečník."),
    ("lurker", "číhající", "kdo čte, ale nepřispívá", "I'm just a lurker here.", "Tady jen čtu, nepíšu."),
    ("ban", "zákaz", "vykázání z platformy", "He got a ban for spamming.", "Dostal ban za spamování."),
    ("ratio", "poměr", "víc reakcí než lajků", "Your post got ratioed.", "Tvůj příspěvek pohořel v reakcích."),
    ("based", "založený", "stojí si za svým, respekt", "That reply was based.", "Ta odpověď byla naprosto v pohodě."),
    ("cope", "vyrovnat se", "smiř se s tím", "Lost again? Cope.", "Zase prohra? Smiř se s tím."),
    ("seethe", "vařit se", "vztekej se (potichu)", "Mad? Stay mad and seethe.", "Naštvaný? Tak se vztekej dál."),
    ("touch grass", "dotkni se trávy", "jdi pryč od počítače", "You need to touch grass.", "Potřebuješ pryč od počítače, mezi lidi."),
    ("doomscrolling", "scrollování zkázy", "donekonečna číst špatné zprávy", "I spent the night doomscrolling.", "Celou noc jsem hltal špatné zprávy."),
    ("ratioed", "vypoměrovaný", "přehlasovaný v reakcích", "His take got ratioed fast.", "Jeho názor rychle pohořel."),
    ("dox", "doxnout", "zveřejnit cizí osobní údaje", "Doxxing someone is illegal.", "Zveřejnit cizí údaje je nelegální."),
    ("ban hammer", "kladivo banu", "pravomoc zabanovat", "The mod swung the ban hammer.", "Moderátor rozdal bany."),
    ("sock puppet", "ponožková loutka", "falešný druhý účet", "He used a sock puppet to praise himself.", "Chválil se přes falešný účet."),
    ("karma", "karma", "body za příspěvky (Reddit)", "That post earned lots of karma.", "Ten příspěvek nasbíral hodně karmy."),
    ("upvote", "hlas nahoru", "dát plus, schválit", "Upvote if you agree.", "Dej plus, jestli souhlasíš."),
    ("downvote", "hlas dolů", "dát mínus", "Don't downvote honest questions.", "Nedávej mínus za upřímné dotazy."),
    ("thread", "vlákno", "série propojených příspěvků", "Read the whole thread.", "Přečti si celé vlákno."),
    ("hashtag", "hashtag", "klíčové slovo s mřížkou", "Use a hashtag to get found.", "Použij hashtag, ať tě najdou."),
    ("viral", "virální", "rychle se šířící", "The clip went viral overnight.", "To video se přes noc rozšířilo všude."),
    ("ratio king", "král poměru", "kdo sbírá víc reakcí (kritika)", "He's the ratio king of comments.", "V komentářích to pořád schytává."),
    ("ban evasion", "obcházení banu", "obcházení zákazu novým účtem", "Ban evasion gets you a longer ban.", "Obcházení banu ti přidá delší trest."),
    ("flame war", "plamenná válka", "vyhrocená online hádka", "The thread turned into a flame war.", "Vlákno se zvrhlo v zuřivou hádku."),
    ("rage bait", "návnada na vztek", "obsah, co schválně rozčiluje", "That post is just rage bait.", "Ten příspěvek má jen rozčilovat."),
    ("brain rot", "hniloba mozku", "obsah co otupuje, závislost na něm", "Too much short video is brain rot.", "Moc krátkých videí ti otupí mozek."),
    ("chronically online", "chronicky online", "kdo je pořád na netu", "That argument is so chronically online.", "Ta hádka je typická pro lidi věčně na netu."),
    ("ratio bait", "návnada na poměr", "příspěvek lákající kritiku", "Ignore the ratio bait.", "Nevšímej si té provokace."),
    ("e-girl", "e-holka", "dívka s online stylem subkultury", "She has an e-girl aesthetic.", "Má styl typický pro online subkulturu."),
    ("emoji", "emoji", "obrázkový znak nálady", "Add an emoji to lighten it.", "Přidej emoji, ať to odlehčíš."),
    ("gg", "dobrá hra", "dobrá hra / je dohráno", "Gg everyone, good game.", "Dobrá hra všem."),
    ("dox attack", "doxovací útok", "útok zveřejněním údajů", "They threatened a dox attack.", "Vyhrožovali zveřejněním údajů."),
    ("lurk", "číhat", "tiše sledovat", "I just lurk in that group.", "V té skupině jen tiše čtu."),
    ("repost", "přeposlání", "znovu sdílený příspěvek", "Stop reposting old memes.", "Přestaň sdílet staré memy dokola."),
    ("subtweet", "podtweet", "narážka, aniž označíš osobu", "That was a subtweet about me.", "To byla narážka na mě, aniž mě označil."),
    ("ratio me", "vypoměruj mě", "vyzvání ke kritice (ironie)", "Wrong opinion? Ratio me then.", "Špatný názor? Tak mě převálcuj."),
    ("alt account", "alternativní účet", "vedlejší účet", "He posts that on his alt account.", "Tohle dává na svůj vedlejší účet."),
    ("mods", "modové", "moderátoři", "The mods deleted the post.", "Moderátoři ten příspěvek smazali."),
    ("ban appeal", "odvolání proti banu", "žádost o zrušení zákazu", "He filed a ban appeal.", "Podal odvolání proti banu."),
    ("ratio loss", "prohra v poměru", "totální porážka v reakcích", "That's a clean ratio loss.", "To je čistá porážka v reakcích."),
    ("og", "originální", "původní, z první generace", "He's an OG of this server.", "Je tu od úplného začátku."),
    ("rt", "přeposlat", "sdílet dál (retweet)", "RT if you agree.", "Sdílej dál, jestli souhlasíš."),
    ("dm me", "napiš mi", "napiš mi soukromě", "Questions? DM me.", "Dotazy? Napiš mi soukromě."),
    ("ratio incoming", "poměr přichází", "blíží se vlna kritiky", "Bad take, ratio incoming.", "Špatný názor, schytáš to."),
    ("ban list", "seznam banů", "seznam zakázaných", "He ended up on the ban list.", "Skončil na seznamu zabanovaných."),
    ("pog", "pog", "výraz nadšení (úžasné)", "Pog, you actually did it!", "Paráda, tys to fakt dokázal!"),
    ("poggers", "poggers", "úžasné, super (z emote)", "New update? Poggers!", "Nová aktualizace? Super!"),
    ("copium", "copium", "klamná útěcha po prohře", "He's on full copium after the loss.", "Po prohře se utěšuje, jak může."),
    ("ratio'd hard", "tvrdě vypoměrovaný", "drtivě převálcovaný v reakcích", "That comment got ratio'd hard.", "Ten komentář pořádně schytal."),
    ("hot link", "horký odkaz", "aktuálně populární odkaz", "Here's the hot link of the day.", "Tady je dnešní žhavý odkaz."),
    ("fr fr", "fakt fakt", "fakt vážně, bez kecu", "That's wild, fr fr.", "To je šílené, fakt vážně."),
    ("ban speedrun", "rychloběh k banu", "rychle si vykoledovat ban", "He did a ban speedrun.", "Ban si vysloužil rekordně rychle."),
    ("read receipts", "potvrzení o přečtení", "info, že zpráva byla přečtena", "Turn off read receipts.", "Vypni potvrzení o přečtení."),
    ("typing...", "píše...", "druhý právě píše zprávu", "She's typing... then stopped.", "Píše... a pak přestala."),
    ("left on read", "zanecháno na přečteno", "zpráva přečtena bez odpovědi", "He left me on read again.", "Zase mi to přečetl a neodepsal."),
    ("ratio energy", "poměrová energie", "atmosféra nadcházející kritiky", "This thread has ratio energy.", "Tohle vlákno vypadá na pořádnou kritiku."),
    ("blue tick", "modré zatržení", "ověřený účet", "He finally got the blue tick.", "Konečně dostal ověřovací odznak."),
    ("ban wave", "vlna banů", "hromadné bany najednou", "A ban wave hit the cheaters.", "Vlna banů smetla podvodníky."),
    ("ratio sandwich", "poměrový sendvič", "obklíčen kritikou ze všech stran", "His reply became a ratio sandwich.", "Jeho odpověď schytala kritiku ze všech stran."),
    ("low key viral", "tiše virální", "potichu populární", "The clip went low key viral.", "To video se potichu rozšířilo."),
    ("screenshot", "snímek obrazovky", "obrázek obrazovky", "Send me a screenshot.", "Pošli mi screenshot."),
    ("ratio confirmed", "poměr potvrzen", "kritika oficiálně zvítězila", "Ratio confirmed, he deleted it.", "Schytal to, tak to smazal."),
    ("ban incoming", "ban přichází", "blíží se zákaz", "Spam again? Ban incoming.", "Zase spam? Letí ban."),
    ("ratio'd to oblivion", "vypoměrovaný do zapomnění", "naprosto rozdrcený kritikou", "His tweet got ratio'd to oblivion.", "Jeho tweet úplně rozcupovali."),
    ("vibe shift", "posun nálady", "změna celkové atmosféry", "There's been a vibe shift online.", "Online nálada se nějak změnila."),
    ("ratio meta", "poměrové meta", "trend hromadné kritiky", "We're in the ratio meta now.", "Teď frčí hromadná kritika."),
    ("ban reason", "důvod banu", "důvod zákazu", "What was the ban reason?", "Jaký byl důvod banu?"),
    ("ratio victory", "poměrové vítězství", "výhra v reakcích", "Sweet ratio victory there.", "Pěkné vítězství v reakcích."),
    ("digital footprint", "digitální stopa", "stopa po sobě na internetu", "Mind your digital footprint.", "Dávej pozor na svou digitální stopu."),
    ("ratio club", "klub poměru", "ti, co schytali kritiku", "Welcome to the ratio club.", "Vítej v klubu těch, co to schytali."),
]
