# Everyday colloquial English with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

DAILY_SPEECH = [
    ("gonna", "jdoucí na", "budu / chystám se (going to)", "I'm gonna call you later.", "Zavolám ti později."),
    ("wanna", "chtít na", "chci (want to)", "Do you wanna grab lunch?", "Nechceš zajít na oběd?"),
    ("gotta", "muset na", "musím (got to)", "I gotta go now.", "Teď už musím jít."),
    ("kinda", "trochu na", "tak nějak, trochu", "I'm kinda tired today.", "Dneska jsem tak nějak unavený."),
    ("sorta", "druhem na", "tak trochu, jakoby", "It's sorta complicated.", "Je to tak trochu složité."),
    ("dunno", "nevím", "nevím (don't know)", "I dunno what to do.", "Nevím, co dělat."),
    ("yeah", "jo", "jo, ano", "Yeah, that sounds good.", "Jo, to zní dobře."),
    ("nope", "ne", "ne, kdepak", "Nope, I haven't seen it.", "Ne, neviděl jsem to."),
    ("yep", "jo", "jo, jasně", "Yep, I'll be there.", "Jo, budu tam."),
    ("nah", "ne", "néé, ani ne", "Nah, I'm good, thanks.", "Néé, jsem v pohodě, díky."),
    ("hang on", "drž se", "počkej moment", "Hang on, I'll check.", "Počkej, mrknu se na to."),
    ("no worries", "žádné starosti", "v pohodě, nic se neděje", "No worries, it happens.", "V pohodě, to se stává."),
    ("my bad", "moje špatné", "moje chyba, pardon", "My bad, I forgot to reply.", "Moje chyba, zapomněl jsem odepsat."),
    ("you bet", "vsadíš se", "jasně, samozřejmě", "You bet I'll help!", "Jasně že pomůžu!"),
    ("for sure", "pro jisté", "určitě, jasně", "For sure, count me in.", "Jasně, počítej se mnou."),
    ("no biggie", "žádný velký", "nic velkého, drobnost", "It's no biggie, forget it.", "Nic velkého, zapomeň na to."),
    ("hold up", "drž nahoru", "počkej chvíli", "Hold up, what did you say?", "Počkej, cos to říkal?"),
    ("chill", "chladit", "klid, v pohodě / relaxovat", "Just chill, it'll be fine.", "Jen klid, bude to dobré."),
    ("take it easy", "ber to lehce", "neber to vážně, v klidu", "Take it easy this weekend.", "O víkendu vypni a odpočiň si."),
    ("never mind", "nikdy mysl", "to nic, nech to být", "Never mind, I'll do it myself.", "To nic, udělám to sám."),
    ("hang tight", "drž pevně", "vydrž, počkej", "Hang tight, help is coming.", "Vydrž, pomoc je na cestě."),
    ("what's the deal", "jaký je obchod", "o co jde, co se děje", "What's the deal with him?", "Co je s ním?"),
    ("no way", "žádná cesta", "to snad ne / v žádném případě", "No way, that's amazing!", "To snad ne, to je úžasné!"),
    ("you got it", "máš to", "jasně, hotovo", "You got it, boss.", "Jasně, šéfe."),
    ("heads up", "hlavy nahoru", "upozornění předem", "Just a heads up, the meeting moved.", "Jen pro info, schůzka se přesunula."),
    ("sounds good", "zní dobře", "to zní dobře, souhlasím", "Sounds good, let's do it.", "Zní to dobře, jdeme do toho."),
    ("got it", "mám to", "chápu, rozumím", "Got it, I'll fix it now.", "Chápu, hned to opravím."),
    ("hang on a sec", "drž se vteřinu", "vydrž vteřinku", "Hang on a sec, I'm coming.", "Vydrž vteřinku, už jdu."),
    ("you know", "ty víš", "no víš, jakoby", "It was, you know, weird.", "Bylo to, no víš, divný."),
    ("I mean", "myslím", "teda, chci říct", "I mean, it could work.", "Teda, mohlo by to fungovat."),
    ("by the way", "u cesty", "mimochodem", "By the way, happy birthday!", "Mimochodem, všechno nejlepší!"),
    ("kind of a big deal", "tak nějak velká věc", "docela důležitá věc/osoba", "He's kind of a big deal here.", "Tady je to docela velké zvíře."),
    ("up to you", "nahoru na tebe", "je to na tobě", "It's totally up to you.", "Je to úplně na tobě."),
    ("fair enough", "spravedlivě dost", "to dává smysl, beru", "Fair enough, you have a point.", "Beru, máš pravdu."),
    ("makes sense", "dělá smysl", "dává to smysl", "Yeah, that makes sense.", "Jo, to dává smysl."),
    ("no problem", "žádný problém", "není problém", "No problem, anytime.", "Není problém, kdykoliv."),
    ("you're welcome", "jsi vítán", "není zač", "You're welcome, glad to help.", "Není zač, rád pomůžu."),
    ("hold on tight", "drž se pevně", "drž se pevně", "Hold on tight, it's bumpy.", "Drž se pevně, je to hrbolaté."),
    ("come on", "pojď na", "no tak / dělej", "Come on, we'll be late!", "No tak, přijdeme pozdě!"),
    ("hang in there", "vydrž tam", "vydrž", "Hang in there, almost done.", "Vydrž, skoro hotovo."),
    ("good for you", "dobré pro tebe", "to ti přeju, výborně", "You passed? Good for you!", "Prošel jsi? To ti přeju!"),
    ("not a chance", "ne šance", "vyloučeno", "Not a chance I'm doing that.", "To v žádném případě dělat nebudu."),
    ("you wish", "ty si přeješ", "to by se ti líbilo", "Me, lose? You wish!", "Já a prohrát? To by se ti líbilo!"),
    ("big time", "velký čas", "pořádně, hodně", "I messed up big time.", "Pořádně jsem to podělal."),
    ("dead tired", "mrtvě unavený", "úplně vyřízený", "I'm dead tired after work.", "Po práci jsem úplně vyřízený."),
    ("starving", "hladovějící", "mám hlad jako vlk", "I'm starving, let's eat.", "Mám hlad jako vlk, jdeme jíst."),
    ("freezing", "mrznoucí", "je hrozná zima", "It's freezing outside.", "Venku je hrozná zima."),
    ("boiling", "vroucí", "je strašné horko", "It's boiling in here.", "Je tu strašné horko."),
    ("a rip-off", "trhání pryč", "předražené, zlodějna", "Ten euros? That's a rip-off.", "Deset euro? To je zlodějna."),
    ("a steal", "krádež", "velmi výhodná koupě", "At that price it's a steal.", "Za tu cenu je to skoro zadarmo."),
    ("hit the spot", "trefit místo", "přesně to, co jsem potřeboval", "That coffee really hit the spot.", "Ta káva byla přesně to, co jsem potřeboval."),
    ("grab a bite", "popadnout sousto", "dát si něco malého k jídlu", "Let's grab a bite before the movie.", "Dáme si něco menšího před filmem."),
    ("call it a night", "nazvat to nocí", "skončit pro dnešek (večer)", "I'm tired, let's call it a night.", "Jsem unavený, končíme pro dnešek."),
    ("a no-brainer", "bez mozku", "úplně jasná volba", "Buying it was a no-brainer.", "Koupit to byla úplně jasná volba."),
    ("gut feeling", "střevní pocit", "vnitřní pocit, tušení", "I have a gut feeling about this.", "Mám z toho takový vnitřní pocit."),
    ("hit me up", "uhoď do mě", "ozvi se mi", "Hit me up when you're free.", "Ozvi se, až budeš mít čas."),
    ("text me", "textuj mě", "napiš mi (zprávu)", "Text me when you arrive.", "Napiš, až dorazíš."),
    ("on my way", "na mé cestě", "už jdu / jsem na cestě", "I'm on my way, five minutes.", "Jsem na cestě, pět minut."),
    ("running late", "běžící pozdě", "mám zpoždění", "Sorry, I'm running late.", "Promiň, mám zpoždění."),
    ("give me a sec", "dej mi vteřinu", "dej mi chvilku", "Give me a sec to think.", "Dej mi chvilku na rozmyšlenou."),
    ("knock it off", "srazit to pryč", "nech toho, přestaň", "Knock it off, that's annoying.", "Nech toho, je to otravné."),
    ("cut it out", "vyřízni to ven", "přestaň s tím", "Cut it out, kids!", "Přestaňte s tím, děti!"),
    ("settle down", "usadit dolů", "uklidni se, zklidni", "Settle down, everyone.", "Uklidněte se, všichni."),
    ("get a grip", "dostat sevření", "vzpamatuj se", "Get a grip, it's not the end.", "Vzpamatuj se, není to konec světa."),
    ("watch your step", "hlídej svůj krok", "dávej pozor (kam šlapeš)", "Watch your step, it's slippery.", "Dávej pozor, klouže to."),
    ("take your time", "vezmi si čas", "nespěchej", "No rush, take your time.", "Žádný spěch, v klidu."),
    ("make yourself at home", "udělej si doma", "udělej si pohodlí", "Come in, make yourself at home.", "Pojď dál, udělej si pohodlí."),
    ("help yourself", "pomoz si sám", "posluž si, vezmi si", "Help yourself to some cake.", "Posluž si dortem."),
    ("suit yourself", "vyhov si sám", "jak myslíš, dělej si co chceš", "Don't want to come? Suit yourself.", "Nechceš jít? Jak myslíš."),
    ("you name it", "ty to pojmenuj", "cokoliv si vzpomeneš", "Pizza, sushi, you name it.", "Pizza, sushi, na co si vzpomeneš."),
    ("long story short", "dlouhý příběh krátký", "abych to zkrátil", "Long story short, we won.", "Abych to zkrátil, vyhráli jsme."),
    ("more or less", "více nebo méně", "víceméně, tak nějak", "It's more or less done.", "Je to víceméně hotové."),
    ("here and there", "tady a tam", "tu a tam, občas", "I travel here and there.", "Tu a tam cestuju."),
    ("now and then", "teď a tehdy", "občas, čas od času", "We meet now and then.", "Občas se vidíme."),
    ("on second thought", "při druhé myšlence", "když o tom tak přemýšlím", "On second thought, let's stay.", "Když o tom tak přemýšlím, zůstaňme."),
    ("to be honest", "být upřímný", "upřímně řečeno", "To be honest, I'm not sure.", "Upřímně, nejsem si jistý."),
    ("come to think of it", "přijít to přemýšlet", "když o tom tak přemýšlím", "Come to think of it, he was right.", "Když o tom tak přemýšlím, měl pravdu."),
    ("as far as I know", "tak daleko jak vím", "pokud vím", "As far as I know, it's open.", "Pokud vím, je otevřeno."),
    ("give it a shot", "dát tomu výstřel", "zkusit to", "Why not give it a shot?", "Proč to nezkusit?"),
    ("give it a go", "dát tomu jít", "zkusit to", "I'll give it a go tomorrow.", "Zítra to zkusím."),
    ("worth a shot", "stojí za výstřel", "stojí to za pokus", "It's worth a shot.", "Stojí to za pokus."),
    ("keep in touch", "drž v dotyku", "zůstaň v kontaktu", "Let's keep in touch.", "Zůstaňme v kontaktu."),
    ("touch base", "dotknout se mety", "spojit se, krátce probrat", "Let's touch base next week.", "Spojíme se příští týden."),
    ("hang out", "viset venku", "trávit spolu čas", "Wanna hang out this weekend?", "Nechceš spolu o víkendu něco podniknout?"),
    ("chill out", "vychladnout", "uklidnit se, odpočívat", "Chill out, it's just a game.", "Uklidni se, je to jen hra."),
    ("freak out", "vyšilovat ven", "zpanikařit, vyšilovat", "Don't freak out, it's okay.", "Nepanikař, je to v pohodě."),
    ("mess up", "zmatkovat nahoru", "podělat, pokazit", "I really messed up.", "Pořádně jsem to pokazil."),
    ("screw up", "zašroubovat nahoru", "zpackat, podělat", "Don't screw this up.", "Tohle nepodělej."),
    ("hang loose", "viset volně", "buď v klidu, pohoda", "Just hang loose, man.", "Hlavně v klidu, kámo."),
    ("good to go", "dobrý na jít", "připravený, hotový", "Bags packed, we're good to go.", "Sbaleno, můžeme vyrazit."),
    ("ASAP", "co nejdřív", "co nejdříve (as soon as possible)", "Send it ASAP, please.", "Pošli to co nejdřív, prosím."),
    ("FYI", "pro tvou informaci", "jen pro informaci", "FYI, the deadline is Monday.", "Jen pro info, termín je v pondělí."),
    ("a heads-up", "hlavy nahoru", "varování dopředu", "Thanks for the heads-up.", "Díky, žes mě varoval dopředu."),
    ("the bottom line", "spodní čára", "závěr, podstata", "The bottom line is we need money.", "Podstatné je, že potřebujeme peníze."),
    ("at the end of the day", "na konci dne", "v konečném důsledku", "At the end of the day, family matters.", "V konečném důsledku jde o rodinu."),
    ("give or take", "dát nebo vzít", "plus mínus, zhruba", "It's 50 km, give or take.", "Je to 50 km, plus mínus."),
    ("around the corner", "za rohem", "blízko, brzy", "Christmas is just around the corner.", "Vánoce jsou za dveřmi."),
    ("a ballpark figure", "číslo z hřiště", "přibližný odhad", "Give me a ballpark figure.", "Řekni mi přibližný odhad."),
    ("in a nutshell", "v ořechové skořápce", "ve zkratce", "In a nutshell, it works.", "Ve zkratce, funguje to."),
]
