# British slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

BRITISH_SLANG = [
    ("mate", "druh", "kámo, kamaráde", "Alright, mate?", "Čau, kámo, jak je?"),
    ("knackered", "vyřízený", "úplně vyčerpaný", "I'm absolutely knackered.", "Jsem úplně na dně."),
    ("gutted", "vykuchaný", "zničený zklamáním", "I was gutted we lost.", "Byl jsem zničený, že jsme prohráli."),
    ("chuffed", "nadšený", "nadšený, potěšený", "I'm well chuffed with this.", "Mám z toho fakt radost."),
    ("cheeky", "drzý", "rošťácký, drzoučký", "That's a cheeky move.", "To je pěkně drzý tah."),
    ("dodgy", "pochybný", "podezřelý, nedůvěryhodný", "That deal looks dodgy.", "Ten obchod vypadá podezřele."),
    ("knackered out", "vyřízený ven", "vyčerpaný na maximum", "The kids are knackered out.", "Děti jsou úplně hotové."),
    ("gobsmacked", "plácnutý do huby", "v naprostém šoku", "I was gobsmacked by the news.", "Z té zprávy jsem zůstal koukat."),
    ("chav", "chav", "křupan z předměstí (hanlivě)", "He dresses like a chav.", "Obléká se jako křupan z předměstí."),
    ("posh", "nóbl", "vznešený, panský", "They live in a posh area.", "Bydlí v nóbl čtvrti."),
    ("quid", "libra", "libra (peníze)", "It cost me twenty quid.", "Stálo mě to dvacet liber."),
    ("bob's your uncle", "Bob je tvůj strýc", "a je to, hotovo", "Press start and Bob's your uncle.", "Zmáčkneš start a je to."),
    ("knees-up", "kolena nahoru", "veselá oslava", "We had a proper knees-up.", "Měli jsme pořádnou oslavu."),
    ("kip", "šlofík", "spánek, zdřímnutí", "I need a quick kip.", "Potřebuju si zdřímnout."),
    ("loo", "záchod", "záchod, toaleta", "Where's the loo?", "Kde je záchod?"),
    ("telly", "bedna", "televize", "It's on the telly tonight.", "Dneska to dávají v televizi."),
    ("brolly", "deštníček", "deštník", "Take a brolly, it's raining.", "Vezmi deštník, prší."),
    ("fortnight", "čtrnáctidenní", "dva týdny", "I'll be back in a fortnight.", "Vrátím se za dva týdny."),
    ("cuppa", "šálínek", "šálek čaje", "Fancy a cuppa?", "Dáš si čaj?"),
    ("biscuit", "suchar", "sušenka", "Have a biscuit with your tea.", "Dej si k čaji sušenku."),
    ("chips", "lupínky", "hranolky", "Fish and chips, please.", "Rybu s hranolky, prosím."),
    ("crisps", "křupky", "brambůrky (chipsy)", "A packet of crisps, please.", "Sáček brambůrků, prosím."),
    ("snog", "líbačka", "francouzský polibek", "They had a snog at the party.", "Na párty se líbali."),
    ("fancy", "fantazírovat", "mít chuť na / být zamilovaný", "Do you fancy a pint?", "Nemáš chuť na pivko?"),
    ("pint", "půllitr", "pivo (půllitr)", "Let's grab a pint.", "Pojďme na pivo."),
    ("pub", "hospoda", "hospoda", "Meet me at the pub.", "Sejdeme se v hospodě."),
    ("bloke", "chlapík", "chlap, týpek", "He's a decent bloke.", "Je to slušnej chlap."),
    ("lad", "mládenec", "kluk, mladík", "He's a good lad.", "Je to dobrej kluk."),
    ("lass", "děvče", "holka, děvče", "She's a lovely lass.", "Je to milá holka."),
    ("innit", "že jo", "že jo, ne (isn't it)", "Cold today, innit?", "Dneska zima, co?"),
    ("blimey", "ty jo", "ty jo, panečku", "Blimey, that was close!", "Ty jo, to bylo o fous!"),
    ("crikey", "jejda", "panečku, jejda", "Crikey, look at the time!", "Jejda, koukni kolik je hodin!"),
    ("bonkers", "praštěný", "úplně bláznivý", "That idea is bonkers.", "Ten nápad je úplně praštěný."),
    ("barmy", "potrhlý", "bláznivý, ztřeštěný", "He's gone completely barmy.", "Úplně se pomátl."),
    ("knackered car", "vyřízené auto", "rozpadající se auto", "His knackered car broke down.", "Jeho rozhrkané auto se porouchalo."),
    ("skint", "švorc", "bez peněz", "I'm totally skint.", "Jsem úplně švorc."),
    ("dosh", "prachy", "peníze", "I've got no dosh left.", "Nezbyly mi žádné prachy."),
    ("naff", "lacinka", "nevkusný, trapný", "That gift is a bit naff.", "Ten dárek je trochu lacinej."),
    ("gobby", "hubatý", "ukecaný, drzý", "She's a bit gobby.", "Je trochu hubatá."),
    ("nosh", "žrádlo", "jídlo", "Let's get some nosh.", "Pojďme něco zakousnout."),
    ("peckish", "mlsný", "mít menší hlad", "I'm feeling a bit peckish.", "Mám takový menší hlad."),
    ("chock-a-block", "nacpaný blokem", "narvaný k prasknutí", "The road was chock-a-block.", "Silnice byla úplně ucpaná."),
    ("dead", "mrtvý", "hrozně, moc (zesílení)", "It's dead easy.", "Je to úplně lehké."),
    ("proper", "řádný", "pořádný, opravdový", "That's a proper meal.", "To je pořádné jídlo."),
    ("sorted", "vyřešený", "vyřízeno, hotovo", "Tickets are sorted.", "Lístky jsou zařízené."),
    ("ta", "díky", "díky", "Ta for the help.", "Díky za pomoc."),
    ("cheers", "na zdraví", "díky / na zdraví", "Cheers, mate!", "Díky, kámo!"),
    ("dead chuffed", "mrtvě nadšený", "nadmíru spokojený", "I'm dead chuffed with my grade.", "Z té známky mám obrovskou radost."),
    ("bants", "srandičky", "škádlení, legrace", "It's just banter, mate.", "To je jen sranda, kámo."),
    ("banter", "škádlení", "vtipné popichování", "We had a good banter.", "Pěkně jsme se popichovali."),
    ("minging", "odporný", "hnusný, ošklivý", "The weather is minging.", "Počasí je hnusné."),
    ("gross", "hrubý", "nechutný", "That's absolutely gross.", "To je úplně nechutné."),
    ("knees", "kolena", "(slang) bolístka / sláb)", "My knees are giving up.", "Kolena mě zlobí."),
    ("manky", "ušmudlaný", "špinavý, zkažený", "These socks are manky.", "Tyhle ponožky jsou ušmudlané."),
    ("wonky", "křivý", "nakřivo, vratký", "The table is a bit wonky.", "Ten stůl je trochu vratký."),
    ("knacker", "kobylkař", "zničit / únava", "That hike will knacker you.", "Z té túry budeš na dně."),
    ("gaff", "barák", "byt, bydliště", "Come round to my gaff.", "Stav se u mě doma."),
    ("dosser", "povaleč", "lenoch, flákač", "Don't be such a dosser.", "Nebuď takový lenoch."),
    ("chuffing", "nadšeně", "zatraceně (mírná nadávka)", "It's chuffing cold out.", "Venku je zatracená zima."),
    ("knockoff", "padělek", "napodobenina značky", "Those trainers are knockoffs.", "Ty tenisky jsou padělky."),
    ("trainers", "trénovači", "tenisky, sportovní boty", "Nice new trainers!", "Pěkné nové tenisky!"),
    ("jumper", "skokan", "svetr", "Put on a jumper, it's cold.", "Obleč si svetr, je zima."),
    ("trousers", "kalhotáče", "kalhoty", "These trousers are too tight.", "Tyhle kalhoty jsou moc těsné."),
    ("nappy", "plenka", "plenka", "The baby needs a new nappy.", "Mimino potřebuje přebalit."),
    ("dummy", "atrapa", "dudlík", "The baby dropped its dummy.", "Mimino upustilo dudlík."),
    ("pram", "kočár", "kočárek", "She pushed the pram to the park.", "Tlačila kočárek do parku."),
    ("queue", "fronta", "fronta, řada", "Join the queue, please.", "Zařaďte se do fronty, prosím."),
    ("waffle", "vafle", "mluvit dlouze a o ničem", "Stop waffling and answer.", "Přestaň plkat a odpověz."),
    ("chunder", "vyzvracet", "pozvracet se", "He chundered after the party.", "Po párty se pozvracel."),
    ("gander", "houser", "letmý pohled", "Have a gander at this.", "Mrkni se na tohle."),
    ("nick", "vroubek", "ukrást / vězení / chytit", "Someone nicked my bike.", "Někdo mi šlohnul kolo."),
    ("grass", "tráva", "donašeč / práskat", "Don't grass on your mates.", "Neprásktej kámoše."),
    ("knees weak", "slabá kolena", "podlamovat se nervozitou", "My knees went weak before the speech.", "Před proslovem se mi podlamovala kolena."),
    ("dishy", "pohledný", "fešácký, atraktivní", "Her new boyfriend is dishy.", "Její nový přítel je fešák."),
    ("fit", "fit", "atraktivní, sexy", "He's well fit.", "Je fakt sexy."),
    ("buzzing", "bzučící", "nadšený, natěšený", "I'm buzzing for the weekend.", "Na víkend se strašně těším."),
    ("sound", "zvukový", "v pohodě, super (o člověku)", "He's a sound guy.", "Je to fajn chlap."),
    ("ace", "eso", "skvělý, super", "That film was ace.", "Ten film byl skvělý."),
    ("brill", "skvěl", "skvělý (brilliant)", "That's brill, thanks!", "To je super, díky!"),
    ("smashing", "rozbíjející", "skvělý, parádní", "We had a smashing time.", "Měli jsme parádní čas."),
    ("dead good", "mrtvě dobrý", "moc dobrý, super", "The food was dead good.", "Jídlo bylo fakt skvělé."),
    ("knees-deep", "po kolena", "až po uši (v něčem)", "I'm knees-deep in work.", "Jsem až po uši v práci."),
    ("gobsmacking", "ohromující", "neuvěřitelný, šokující", "The price was gobsmacking.", "Ta cena byla šokující."),
    ("scran", "žrádlo", "jídlo, žvanec", "Time for some scran.", "Čas se najíst."),
    ("butty", "chlebíček", "sendvič", "I made a bacon butty.", "Udělal jsem si slaninový sendvič."),
    ("chuffed to bits", "nadšený na kousky", "nadšený k nepopsání", "She was chuffed to bits.", "Byla nadšením bez sebe."),
    ("taking the mick", "brát mick", "dělat si legraci, provokovat", "Are you taking the mick?", "Děláš si srandu?"),
    ("on the lash", "na biči", "pařit, chlastat", "We're going on the lash.", "Jdeme se pořádně opít."),
    ("knees up Mother Brown", "kolena nahoru matko Brownová", "rozjetá lidová oslava", "It turned into a knees up.", "Změnilo se to v pořádnou veselici."),
    ("gutting", "kuchání", "hrozně zklamávající", "Losing like that is gutting.", "Takhle prohrát je hrozné zklamání."),
    ("knickers", "kalhotky", "spodní prádlo (dámské)", "Don't get your knickers in a twist.", "Nedělej z toho vědu."),
    ("plonker", "trouba", "hlupák, blbec", "Don't be a plonker.", "Nebuď trouba."),
    ("muppet", "muppet", "trumbera, popleta", "He's such a muppet.", "Je to takový popleta."),
    ("numpty", "nešika", "popleta, nemehlo", "I'm such a numpty sometimes.", "Někdy jsem fakt nemehlo."),
    ("knees trembling", "třesoucí se kolena", "klepat se strachy", "I was knees trembling before the exam.", "Před zkouškou se mi klepala kolena."),
    ("dead chuffed mate", "mrtvě nadšený druhu", "kámo, jsem nadšený", "Dead chuffed, mate, ta!", "Mám obrovskou radost, kámo, díky!"),
    ("rubbish", "smetí", "blbost, nesmysl / odpadky", "That's absolute rubbish.", "To je úplný nesmysl."),
    ("bin", "popelnice", "koš na odpadky", "Throw it in the bin.", "Hoď to do koše."),
    ("flat", "byt", "byt", "We rented a small flat.", "Pronajali jsme si malý byt."),
    ("lift", "zvednutí", "výtah", "Take the lift to the third floor.", "Vezmi výtah do třetího patra."),
    ("knee-high", "po kolena vysoký", "úplně malý/nízký", "I knew him when he was knee-high.", "Znal jsem ho odmalička."),
]
