# Business slang/jargon with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

BUSINESS = [
    ("bottom line", "spodní čára", "podstata / čistý zisk", "The bottom line is profit.", "Podstatné je, jestli je zisk."),
    ("ballpark figure", "číslo z hřiště", "přibližný odhad", "Give me a ballpark figure.", "Dej mi přibližný odhad."),
    ("cash cow", "dojná kráva", "stabilní zdroj příjmů", "That product is our cash cow.", "Ten produkt je naše dojná kráva."),
    ("game changer", "měnič hry", "převratná novinka", "This tech is a game changer.", "Tahle technologie všechno mění."),
    ("win-win", "výhra-výhra", "výhodné pro obě strany", "It's a win-win deal.", "Je to výhodné pro obě strany."),
    ("scale up", "škálovat nahoru", "rozšiřovat, růst", "We need to scale up fast.", "Musíme rychle růst."),
    ("startup", "rozjezdovka", "nově vznikající firma", "He founded a startup.", "Založil startup."),
    ("unicorn", "jednorožec", "startup s hodnotou přes miliardu", "Their startup became a unicorn.", "Jejich startup se stal jednorožcem."),
    ("burn rate", "rychlost spalování", "tempo utrácení peněz", "Our burn rate is too high.", "Utrácíme peníze moc rychle."),
    ("runway", "ranvej", "doba, na kterou vydrží peníze", "We have six months of runway.", "Peníze nám vydrží šest měsíců."),
    ("pivot", "otočka", "změna obchodního směru", "The company had to pivot.", "Firma musela změnit směr."),
    ("disrupt", "narušit", "převratně změnit trh", "They want to disrupt banking.", "Chtějí převrátit bankovnictví."),
    ("roi", "návratnost investice", "návratnost investice", "What's the ROI on this?", "Jaká je tu návratnost?"),
    ("b2b", "firma firmě", "obchod mezi firmami", "We're a B2B company.", "Jsme B2B firma."),
    ("b2c", "firma zákazníkovi", "prodej koncovým zákazníkům", "Their model is B2C.", "Jejich model je prodej koncovým zákazníkům."),
    ("market share", "podíl na trhu", "podíl na trhu", "We gained market share.", "Získali jsme podíl na trhu."),
    ("value proposition", "nabídka hodnoty", "jádro nabídky pro zákazníka", "What's your value proposition?", "Co konkrétně nabízíš zákazníkovi?"),
    ("elevator pitch", "výtahová prezentace", "krátké představení nápadu", "Give me your elevator pitch.", "Řekni mi to ve zkratce."),
    ("low margin", "nízká marže", "malý zisk z prodeje", "It's a low margin business.", "Je to byznys s malou marží."),
    ("high margin", "vysoká marže", "velký zisk z prodeje", "Software is high margin.", "Software má vysokou marži."),
    ("overhead", "režie", "fixní provozní náklady", "We cut overhead costs.", "Snížili jsme režijní náklady."),
    ("cash flow", "tok hotovosti", "tok peněz", "Cash flow is tight.", "Máme napjatý tok peněz."),
    ("in the black", "v černém", "v zisku", "We're finally in the black.", "Konečně jsme v zisku."),
    ("in the red", "v červeném", "ve ztrátě", "The quarter ended in the red.", "Čtvrtletí skončilo ve ztrátě."),
    ("break even", "vyrovnat", "dostat se na nulu", "We broke even this year.", "Letos jsme se dostali na nulu."),
    ("due diligence", "náležitá péče", "důkladná prověrka", "Do your due diligence first.", "Nejdřív si to pořádně prověř."),
    ("leverage", "páka", "využít ve svůj prospěch", "Leverage your network.", "Využij své kontakty."),
    ("synergize", "synergizovat", "spojit síly pro větší efekt", "The merger should synergize teams.", "Fúze by měla spojit síly týmů."),
    ("touch base", "dotknout se mety", "krátce se spojit", "Let's touch base next week.", "Příští týden se spojíme."),
    ("close the deal", "uzavřít obchod", "uzavřít obchod", "We finally closed the deal.", "Konečně jsme ten obchod uzavřeli."),
    ("seal the deal", "zpečetit obchod", "definitivně dohodnout", "A dinner sealed the deal.", "Večeře to zpečetila."),
    ("hard sell", "tvrdý prodej", "agresivní prodejní tlak", "I don't like the hard sell.", "Nemám rád agresivní vnucování."),
    ("soft sell", "měkký prodej", "nenápadný prodej", "They used a soft sell.", "Použili nenápadný přístup."),
    ("upsell", "doprodej výš", "prodej dražší varianty", "The waiter tried to upsell.", "Číšník se snažil prodat dražší variantu."),
    ("cross-sell", "křížový prodej", "prodej souvisejícího zboží", "We cross-sell accessories.", "Doprodáváme doplňky."),
    ("lead", "vodítko", "potenciální zákazník", "We got a hot lead.", "Máme nadějného zájemce."),
    ("pipeline", "potrubí", "seznam rozpracovaných obchodů", "Our sales pipeline is full.", "Máme plný seznam rozjednaných obchodů."),
    ("conversion", "konverze", "proměna zájemce v zákazníka", "Our conversion rate rose.", "Vzrostla nám míra konverze."),
    ("churn", "odliv", "odchod zákazníků", "We need to reduce churn.", "Musíme snížit odliv zákazníků."),
    ("retention", "udržení", "udržení zákazníků", "Customer retention is key.", "Udržení zákazníků je klíčové."),
    ("benchmark", "měřítko", "srovnávací standard", "Let's benchmark competitors.", "Porovnejme se s konkurencí."),
    ("market fit", "soulad s trhem", "produkt sedící trhu", "We found product-market fit.", "Náš produkt konečně sedí trhu."),
    ("bandwidth", "šířka pásma", "volná kapacita", "I don't have the bandwidth for this.", "Na tohle nemám kapacitu."),
    ("low-hanging fruit", "nízko visící ovoce", "snadné zisky", "Target the low-hanging fruit first.", "Nejdřív si vezmi to snadné."),
    ("moving forward", "posun vpřed", "od teď, do budoucna", "Moving forward, we'll meet weekly.", "Od teď se budeme scházet týdně."),
    ("circle back", "obkroužit zpět", "vrátit se k tématu", "Let's circle back tomorrow.", "Vrátíme se k tomu zítra."),
    ("deep dive", "hluboký ponor", "důkladný rozbor", "We did a deep dive on sales.", "Pořádně jsme rozebrali prodeje."),
    ("move the needle", "pohnout ručičkou", "výrazně ovlivnit výsledek", "This campaign moves the needle.", "Tahle kampaň skutečně zabírá."),
    ("disruptor", "narušitel", "firma měnící trh", "They're a disruptor in retail.", "Jsou narušitelem v maloobchodě."),
    ("market leader", "vůdce trhu", "firma s největším podílem", "We're the market leader.", "Jsme jednička na trhu."),
    ("first mover", "první v pohybu", "kdo vstoupí na trh první", "Being a first mover has perks.", "Být první na trhu má výhody."),
    ("bottleneck", "hrdlo láhve", "úzké místo bránící postupu", "Production is the bottleneck.", "Úzkým místem je výroba."),
    ("streamline", "zefektivnit", "zjednodušit proces", "We streamlined operations.", "Zefektivnili jsme provoz."),
    ("outsource", "zajistit zvenčí", "zadat práci externě", "We outsource support.", "Podporu zajišťujeme externě."),
    ("in-house", "v domě", "vlastními silami", "We build it in-house.", "Děláme to vlastními silami."),
    ("ramp up", "rozjet nahoru", "navyšovat aktivitu", "We'll ramp up marketing.", "Rozjedeme marketing naplno."),
    ("wind down", "stáhnout dolů", "utlumovat činnost", "They're winding down the branch.", "Utlumují tu pobočku."),
    ("blue chip", "modrý žeton", "stabilní špičková firma", "Invest in blue chip stocks.", "Investuj do prověřených akcií."),
    ("bear market", "medvědí trh", "klesající trh", "We're in a bear market.", "Jsme v klesajícím trhu."),
    ("bull market", "býčí trh", "rostoucí trh", "A bull market boosts confidence.", "Rostoucí trh dodává důvěru."),
    ("market cap", "tržní kapitalizace", "tržní hodnota firmy", "Their market cap doubled.", "Jejich tržní hodnota se zdvojnásobila."),
    ("ipo", "vstup na burzu", "první veřejná nabídka akcií", "The company filed for an IPO.", "Firma chystá vstup na burzu."),
    ("equity", "podíl", "vlastnický podíl", "She owns equity in the firm.", "Vlastní podíl ve firmě."),
    ("stakeholder", "držitel podílu", "zainteresovaná strana", "Keep stakeholders informed.", "Informuj zainteresované strany."),
    ("shareholder", "akcionář", "vlastník akcií", "Shareholders approved the plan.", "Akcionáři plán schválili."),
    ("vc", "rizikový kapitál", "investor do startupů", "A VC funded the round.", "Kolo financoval rizikový investor."),
    ("angel investor", "andělský investor", "soukromý raný investor", "An angel investor backed us.", "Podpořil nás soukromý investor."),
    ("seed round", "zárodečné kolo", "první investiční kolo", "We closed our seed round.", "Uzavřeli jsme první investiční kolo."),
    ("valuation", "ocenění", "hodnota firmy", "Their valuation is sky-high.", "Jejich ocenění je astronomické."),
    ("exit", "odchod", "prodej/odprodej firmy", "They planned a clean exit.", "Plánovali čistý odchod z firmy."),
    ("merger", "fúze", "spojení firem", "The merger was approved.", "Fúze byla schválena."),
    ("acquisition", "akvizice", "převzetí firmy", "It was a strategic acquisition.", "Byla to strategická akvizice."),
    ("hostile takeover", "nepřátelské převzetí", "převzetí proti vůli vedení", "They feared a hostile takeover.", "Báli se nepřátelského převzetí."),
    ("market saturation", "nasycení trhu", "přeplněný trh", "The market is saturated.", "Trh je nasycený."),
    ("price point", "cenový bod", "nastavená cena", "Find the right price point.", "Najdi správnou cenu."),
    ("loss leader", "ztrátový tahák", "levné zboží lákající zákazníky", "Milk is a loss leader.", "Mléko je ztrátový tahák."),
    ("brand awareness", "povědomí o značce", "známost značky", "We boosted brand awareness.", "Zvýšili jsme povědomí o značce."),
    ("market research", "průzkum trhu", "průzkum trhu", "Do market research first.", "Nejdřív udělej průzkum trhu."),
    ("target audience", "cílové publikum", "cílová skupina", "Know your target audience.", "Znej svou cílovou skupinu."),
    ("niche", "nika", "úzce zaměřený trh", "We found a profitable niche.", "Našli jsme ziskovou niku."),
    ("scalable", "škálovatelný", "schopný růstu", "The model is scalable.", "Ten model lze snadno rozšířit."),
    ("lean", "štíhlý", "s minimem plýtvání", "We run a lean operation.", "Fungujeme úsporně."),
    ("agile", "agilní", "pružný způsob práce", "We use an agile approach.", "Pracujeme agilně."),
    ("kpi", "klíčový ukazatel", "ukazatel výkonu", "Sales is our main KPI.", "Hlavní ukazatel je prodej."),
    ("quota", "kvóta", "prodejní cíl", "He hit his quota early.", "Splnil svůj cíl s předstihem."),
    ("commission", "provize", "odměna z prodeje", "She works on commission.", "Pracuje za provizi."),
    ("retainer", "zálohová smlouva", "pravidelná platba za služby", "We pay them a monthly retainer.", "Platíme jim měsíční paušál."),
    ("invoice", "faktura", "účetní doklad k platbě", "Send the invoice today.", "Pošli fakturu ještě dnes."),
    ("net 30", "splatnost 30", "splatnost do 30 dnů", "Our terms are net 30.", "Máme splatnost 30 dní."),
    ("markup", "přirážka", "navýšení ceny nad náklady", "The markup is too high.", "Ta přirážka je moc vysoká."),
    ("overpriced", "předražený", "příliš drahý", "It's totally overpriced.", "Je to úplně předražené."),
    ("undercut", "podseknout", "nabídnout nižší cenu", "They undercut our prices.", "Podsekli naše ceny."),
    ("market dip", "pokles trhu", "dočasný propad trhu", "Buy during a market dip.", "Nakup při poklesu trhu."),
    ("bullish", "býčí", "optimistický (růst)", "Investors are bullish.", "Investoři jsou optimističtí."),
    ("bearish", "medvědí", "pesimistický (pokles)", "Analysts turned bearish.", "Analytici zpesimističtěli."),
    ("liquidity", "likvidita", "dostupnost hotovosti", "We need more liquidity.", "Potřebujeme víc hotovosti."),
    ("red ink", "červený inkoust", "ztráty v účetnictví", "The report is full of red ink.", "Výkaz je plný ztrát."),
    ("golden handshake", "zlatý stisk ruky", "vysoké odstupné", "The CEO got a golden handshake.", "Šéf dostal tučné odstupné."),
    ("golden parachute", "zlatý padák", "odstupné pro vedení", "His contract has a golden parachute.", "Ve smlouvě má zlatý padák."),
    ("market entry", "vstup na trh", "vstup na nový trh", "Plan your market entry carefully.", "Vstup na trh si dobře naplánuj."),
    ("profit margin", "zisková marže", "podíl zisku z tržeb", "Our profit margin improved.", "Zlepšila se nám zisková marže."),
]
