# Dating slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

DATING = [
    ("crush", "drcení", "platonická zamilovanost", "I have a crush on him.", "Jsem do něj zabouchnutá."),
    ("ghosting", "duchaření", "náhlé přestání komunikace", "Ghosting is so rude.", "Přestat se ozývat je hrozně neslušné."),
    ("breadcrumbing", "drobkování", "udržovat zájem bez skutečného zájmu", "He's just breadcrumbing me.", "Jen mě vodí za nos."),
    ("benching", "lavičkování", "držet někoho v záloze", "She's benching three guys.", "Drží si tři kluky v záloze."),
    ("catfishing", "rybaření na sumce", "vydávat se za někoho jiného online", "Watch out for catfishing.", "Pozor na falešné profily."),
    ("situationship", "situačnívztah", "vztah bez jasného statusu", "We're in a situationship.", "Jsme v nějakém nejasném vztahu."),
    ("friends with benefits", "přátelé s výhodami", "kamarádi i s intimitou", "They're just friends with benefits.", "Jsou jen kamarádi s výhodami."),
    ("the one", "ten pravý", "životní láska", "I think she's the one.", "Myslím, že je to ta pravá."),
    ("hit it off", "trefit to", "okamžitě si sednout", "We really hit it off.", "Hned jsme si sedli."),
    ("ask out", "pozvat ven", "pozvat na rande", "He finally asked her out.", "Konečně ji pozval na rande."),
    ("stand up", "postavit", "nepřijít na rande", "He stood me up last night.", "Včera mi nepřišel na rande."),
    ("hook up", "zaháknout se", "krátká intimní známost", "They hooked up at the party.", "Na párty spolu skončili."),
    ("make out", "udělat ven", "intenzivně se líbat", "They made out in the car.", "Líbali se v autě."),
    ("dtr", "definovat vztah", "vyjasnit si vztah", "We need to DTR soon.", "Brzy si musíme vyjasnit vztah."),
    ("lead on", "vést dál", "vodit za nos", "Don't lead him on.", "Nevoď ho za nos."),
    ("settle down", "usadit se", "usadit se, založit rodinu", "They're ready to settle down.", "Jsou připravení se usadit."),
    ("on the rocks", "na skalách", "vztah v krizi", "Their marriage is on the rocks.", "Jejich manželství je v krizi."),
    ("the ex", "bývalý", "bývalý partner", "Her ex keeps texting.", "Její bývalý jí pořád píše."),
    ("rebound", "odraz", "vztah hned po rozchodu", "He's just a rebound.", "Je to jen náhrada po rozchodu."),
    ("third wheel", "třetí kolo", "nadbytečný u páru", "I felt like a third wheel.", "Připadal jsem si jako páté kolo u vozu."),
    ("blind date", "slepé rande", "rande s neznámým", "My friend set up a blind date.", "Kamarádka mi domluvila rande naslepo."),
    ("swipe right", "přejet vpravo", "schválit profil (zájem)", "I swiped right on her.", "Dal jsem jí lajk."),
    ("swipe left", "přejet vlevo", "odmítnout profil", "Swipe left if not interested.", "Přejeď vlevo, když nemáš zájem."),
    ("match", "shoda", "vzájemný zájem na seznamce", "We matched yesterday.", "Včera nám to spárovalo."),
    ("slide into dms", "vklouznout do zpráv", "napsat někomu soukromě se zájmem", "He slid into my DMs.", "Napsal mi do soukromé schránky."),
    ("love bombing", "bombardování láskou", "zahltit city pro získání kontroly", "That's classic love bombing.", "To je klasické bombardování láskou."),
    ("red flag", "červená vlajka", "varovný signál ve vztahu", "Lying is a big red flag.", "Lhaní je velký varovný signál."),
    ("green flag", "zelená vlajka", "dobré znamení u partnera", "Kindness is a green flag.", "Laskavost je dobré znamení."),
    ("the talk", "ten rozhovor", "rozhovor o vztahu", "We finally had the talk.", "Konečně jsme si promluvili o vztahu."),
    ("dump", "vyklopit", "dát kopačky", "She dumped him by text.", "Dala mu kopačky přes zprávu."),
    ("get dumped", "být vyklopen", "dostat kopačky", "He got dumped last week.", "Minulý týden dostal kopačky."),
    ("break up", "rozejít se", "ukončit vztah", "They broke up amicably.", "Rozešli se v dobrém."),
    ("get back together", "dát se zpět dohromady", "znovu se dát dohromady", "They got back together.", "Zase se dali dohromady."),
    ("puppy love", "štěněčí láska", "naivní mladá láska", "It was just puppy love.", "Byla to jen klukovská zamilovanost."),
    ("love at first sight", "láska na první pohled", "láska na první pohled", "It was love at first sight.", "Byla to láska na první pohled."),
    ("out of my league", "mimo mou ligu", "nedosažitelný/lepší než já", "She's out of my league.", "Na ni nemám."),
    ("settle", "usadit", "spokojit se s méně", "Don't settle for less.", "Nespokojuj se s míň."),
    ("the spark", "jiskra", "vzájemná chemie", "There was no spark.", "Nepřeskočila jiskra."),
    ("chemistry", "chemie", "přitažlivost mezi lidmi", "We have great chemistry.", "Je mezi námi skvělá chemie."),
    ("baggage", "zavazadlo", "emoční zátěž z minulosti", "He has a lot of baggage.", "Táhne si toho z minulosti hodně."),
    ("commitment", "závazek", "ochota k vážnému vztahu", "He's scared of commitment.", "Bojí se závazku."),
    ("cuffing season", "období pout", "zima, kdy lidé hledají vztah", "It's cuffing season again.", "Zase je čas, kdy si lidi hledají někoho na zimu."),
    ("dry texting", "suché psaní", "nezáživné, strohé psaní", "His dry texting is a turn-off.", "Jeho strohé zprávy mě odrazují."),
    ("turn-off", "vypnutí", "co odrazuje", "Arrogance is a turn-off.", "Arogance odrazuje."),
    ("turn-on", "zapnutí", "co přitahuje", "Confidence is a turn-on.", "Sebevědomí přitahuje."),
    ("player", "hráč", "kdo si jen pohrává s city", "Watch out, he's a player.", "Pozor, je to záletník."),
    ("flirt", "flirtovat", "koketovat", "She loves to flirt.", "Ráda flirtuje."),
    ("wingman", "křídelník", "kdo pomáhá kamarádovi sbalit", "Be my wingman tonight.", "Buď dneska můj parťák na balení."),
    ("dtf", "připravený na to", "ochotný k intimnosti", "He made it clear he's DTF.", "Dal jasně najevo, že má zájem."),
    ("netflix and chill", "netflix a pohoda", "schůzka s intimním podtextem", "He invited me to Netflix and chill.", "Pozval mě 'na film', však víš."),
    ("pillow talk", "polštářové povídání", "důvěrný hovor v posteli", "We had some pillow talk.", "Povídali jsme si v posteli."),
    ("settle for", "spokojit se s", "vzít zavděk", "She refused to settle for him.", "Odmítla vzít zavděk."),
    ("on a break", "na pauze", "dočasné přerušení vztahu", "We're on a break.", "Dali jsme si pauzu."),
    ("long distance", "na dálku", "vztah na dálku", "Long distance is hard.", "Vztah na dálku je těžký."),
    ("the ick", "ošklivost", "náhlá nechuť k partnerovi", "He gave me the ick.", "Najednou se mi z něj udělalo nanic."),
    ("simp", "simp", "kdo se přehnaně snaží o někoho", "He's simping for her.", "Lísá se k ní až moc."),
    ("thirsty", "žíznivý", "nápadně toužící po pozornosti", "Those comments are so thirsty.", "Ty komentáře jsou zoufale lačné po pozornosti."),
    ("hard launch", "tvrdé spuštění", "veřejné oznámení vztahu", "They did a hard launch online.", "Veřejně oznámili vztah na sítích."),
    ("soft launch", "měkké spuštění", "nenápadný náznak vztahu", "She soft launched her boyfriend.", "Naznačila vztah, aniž ho ukázala."),
    ("dating roster", "seznam rande", "více současně oslovovaných lidí", "He has a whole dating roster.", "Má celý seznam lidí, se kterými randí."),
    ("slow fade", "pomalé mizení", "postupné vytrácení zájmu", "He's doing a slow fade.", "Pomalu se vytrácí."),
    ("orbiting", "obíhání", "sledovat ex online bez kontaktu", "My ex is orbiting my stories.", "Bývalý mi pořád kouká na story."),
    ("cushioning", "polstrování", "držet si zálohu při vztahu", "He's cushioning with his ex.", "Drží si zálohu u bývalé."),
    ("zombieing", "zombíkování", "ghoster se náhle vrátí", "He ghosted, then started zombieing.", "Zmizel a pak se najednou vrátil."),
    ("kittenfishing", "koťátkaření", "mírné přikrášlení profilu", "His photos were kittenfishing.", "Fotky měl pěkně přikrášlené."),
    ("micro-cheating", "mikropodvádění", "drobné nevěry bez fyzična", "Liking exes' photos is micro-cheating.", "Lajkovat fotky bývalých je malá nevěra."),
    ("exclusive", "exkluzivní", "spolu jen ti dva", "Are we exclusive now?", "Jsme teď spolu jen my dva?"),
    ("seeing someone", "vidět někoho", "s někým chodit (zatím volně)", "I'm seeing someone right now.", "Teď s někým chodím."),
    ("taken", "zabraný", "už zadaný", "Sorry, I'm taken.", "Promiň, jsem zadaná."),
    ("single", "svobodný", "nezadaný", "I'm happily single.", "Jsem spokojeně svobodný."),
    ("settle down vibes", "vibrace usazení", "nálada na vážný vztah", "He gives settle down vibes.", "Působí, že se chce usadit."),
    ("dating app", "seznamovací aplikace", "appka na seznamování", "We met on a dating app.", "Poznali jsme se přes seznamku."),
    ("first date", "první rande", "první schůzka", "Our first date was great.", "První rande bylo super."),
    ("the friend zone", "kamarádská zóna", "kamarád bez šance na vztah", "He's stuck in the friend zone.", "Uvízl v kamarádské zóně."),
    ("crushing on", "drtit na", "být zamilovaný do", "She's crushing on her coworker.", "Je zabouchnutá do kolegy."),
    ("settle the score", "vyrovnat skóre", "vyřešit si to (po rozchodu)", "They settled the score calmly.", "Vyřešili si to v klidu."),
    ("rebound fling", "odrazové flirtování", "krátký poměr po rozchodu", "It was just a rebound fling.", "Byla to jen náplast po rozchodu."),
    ("power couple", "mocný pár", "úspěšný, obdivovaný pár", "They're a real power couple.", "Jsou opravdový vysněný pár."),
    ("relationship goals", "cíle vztahu", "vzorový pár, ideál", "You two are relationship goals.", "Vy dva jste ideální pár."),
    ("settle in", "zabydlet se", "zabydlet se ve vztahu", "They settled in nicely together.", "Pěkně se spolu sehráli."),
    ("date night", "rande večer", "společný večer páru", "Friday is our date night.", "Pátek je náš společný večer."),
    ("puppy eyes", "štěněčí oči", "prosebný roztomilý pohled", "She gave me puppy eyes.", "Koukala na mě jako štěňátko."),
    ("butterflies", "motýli", "nervózní zamilovanost", "I get butterflies around her.", "Mám z ní motýly v břiše."),
    ("head over heels", "hlavou přes paty", "po uši zamilovaný", "He's head over heels for her.", "Je do ní zamilovaný až po uši."),
    ("settle for less", "spokojit se s méně", "vzít zavděk horším", "Never settle for less than you deserve.", "Nikdy se nespokojuj s míň, než si zasloužíš."),
    ("dealbreaker", "ukončovač dohody", "nepřekročitelná podmínka", "Smoking is a dealbreaker for me.", "Kouření je pro mě stopka."),
    ("PDA", "veřejné projevy náklonnosti", "mazlení na veřejnosti", "Too much PDA, guys.", "Až moc se před lidmi mazlíte."),
    ("settle a crush", "vyřešit zamilovanost", "vyznat se ze zamilovanosti", "He finally settled his crush by confessing.", "Konečně se vyznal ze své zamilovanosti."),
    ("hopeless romantic", "beznadějný romantik", "velký romantik", "I'm a hopeless romantic.", "Jsem beznadějný romantik."),
    ("settle the date", "domluvit termín rande", "domluvit se na rande", "Let's settle the date for Saturday.", "Domluvme rande na sobotu."),
    ("ghosted again", "zase oduchařen", "znovu opuštěn bez slova", "I got ghosted again.", "Zase se mi přestal ozývat."),
    ("perfect match", "dokonalá shoda", "ideální partner", "You two are a perfect match.", "Vy dva se k sobě dokonale hodíte."),
    ("settle nerves", "uklidnit nervy", "zklidnit trému před rande", "I took a walk to settle my nerves before the date.", "Před rande jsem se prošel, abych zklidnil nervy."),
    ("commitment-phobe", "fobik ze závazku", "kdo se bojí vážného vztahu", "He's a total commitment-phobe.", "Strašně se bojí závazku."),
    ("soulmate", "spřízněná duše", "spřízněná duše", "I finally found my soulmate.", "Konečně jsem našel spřízněnou duši."),
    ("dating dry spell", "rande sucho", "delší období bez rande", "I'm in a dating dry spell.", "Mám delší pauzu od randění."),
    ("settle down soon", "brzy se usadit", "chystat se založit rodinu", "They want to settle down soon.", "Chtějí se brzy usadit."),
    ("text back", "napsat zpět", "odepsat na zprávu", "He never texts back.", "Nikdy neodepíše."),
    ("double date", "dvojité rande", "rande dvou párů", "Let's go on a double date.", "Pojďme na rande ve čtyřech."),
]
