# Gaming slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

GAMING = [
    ("gg", "dobrá hra", "dobrá hra (pozdrav po zápase)", "Gg, well played everyone.", "Dobrá hra, všem se to povedlo."),
    ("ez", "lehké", "easy, snadná výhra", "Ez win, no struggle.", "Lehká výhra, žádný boj."),
    ("noob", "noob", "začátečník, nezkušený hráč", "Don't be toxic to noobs.", "Nebuď zlý na začátečníky."),
    ("pro", "profík", "zkušený, skvělý hráč", "That move was so pro.", "Ten tah byl fakt profi."),
    ("camper", "kempař", "kdo číhá na jednom místě", "Stop being a camper.", "Přestaň kempit na jednom místě."),
    ("spawn", "vznik", "místo, kde se hráč objeví", "Wait for me at spawn.", "Počkej na mě na spawnu."),
    ("respawn", "znovuzrození", "znovuobjevení po smrti", "I'll respawn in five seconds.", "Za pět vteřin se vrátím do hry."),
    ("loot", "kořist", "získaná výbava/odměny", "We found great loot.", "Našli jsme skvělou kořist."),
    ("grind", "dřít", "opakovat činnost pro postup", "I'm grinding for levels.", "Dřu, abych nabral levely."),
    ("buff", "vylepšení", "posílení postavy/schopnosti", "They buffed the sniper.", "Posílili sniperku."),
    ("nerf", "oslabení", "oslabení postavy/schopnosti", "They nerfed my main.", "Oslabili mou hlavní postavu."),
    ("op", "přesilový", "přesilová, nevyvážená věc (overpowered)", "That weapon is so OP.", "Ta zbraň je úplně přesílená."),
    ("meta", "meta", "aktuálně nejlepší strategie", "Shotguns are the current meta.", "Brokovnice jsou teď nejlepší volba."),
    ("aggro", "agro", "přitáhnout pozornost nepřátel", "Don't pull aggro early.", "Nepřitahuj nepřátele moc brzy."),
    ("tank", "tank", "postava držící poškození", "You play tank, I'll heal.", "Ty hraj tanka, já budu léčit."),
    ("dps", "poškození za vteřinu", "poškození / útočná role", "We need more DPS.", "Potřebujeme víc poškození."),
    ("heal", "léčit", "léčit spoluhráče", "Heal me, I'm low!", "Vyléč mě, mám málo života!"),
    ("aoe", "plošný efekt", "plošné poškození (area of effect)", "Use an AoE on the group.", "Použij plošný útok na skupinu."),
    ("cooldown", "ochlazení", "doba do dalšího použití schopnosti", "My ult is on cooldown.", "Moje ultimátka se nabíjí."),
    ("ult", "ultimátka", "nejsilnější schopnost", "Save your ult for the boss.", "Schovej si ultimátku na bosse."),
    ("clutch", "spojka", "vítězství v beznadějné situaci", "He clutched the round 1v3.", "Vyhrál to kolo sám proti třem."),
    ("frag", "frag", "zabití soupeře", "Nice frag!", "Pěkné zabití!"),
    ("kill", "zabití", "vyřazení soupeře", "That was a clean kill.", "To bylo čisté zabití."),
    ("ks", "kradení zabití", "ukradení zabití spoluhráči", "Stop KSing my kills.", "Přestaň mi krást zabití."),
    ("smurf", "smurf", "zkušený hráč na novém účtu", "He's a smurf, way too good.", "Je to smurf, je moc dobrý."),
    ("lag", "zpoždění", "trhání kvůli pingu", "Sorry, I'm lagging hard.", "Promiň, hrozně mi to seká."),
    ("ping", "ping", "odezva spojení", "My ping is too high.", "Mám moc vysoký ping."),
    ("afk", "od klávesnice", "nepřítomný u hry", "He's afk, we're a man down.", "Je pryč od hry, jsme o hráče míň."),
    ("gank", "přepad", "přepadení nepřítele ve více lidech", "Watch out for a gank.", "Dej pozor na přepad."),
    ("feed", "krmit", "zbytečně umírat a posilovat soupeře", "Stop feeding the enemy.", "Přestaň posilovat soupeře umíráním."),
    ("carry", "nést", "táhnout tým k výhře", "He carried the whole game.", "Celou hru táhl sám."),
    ("throw", "zahodit", "prohrát vyhranou hru chybou", "Don't throw the lead!", "Nezahoď ten náskok!"),
    ("rage quit", "vztekem odejít", "naštvaně opustit hru", "He rage quit after dying.", "Po smrti naštvaně odešel."),
    ("tilt", "naklonění", "ztratit nervy a hrát hůř", "I'm on tilt, need a break.", "Ztrácím nervy, potřebuju pauzu."),
    ("toxic", "toxický", "hráč co uráží a kazí náladu", "That chat was super toxic.", "Ten chat byl hrozně toxický."),
    ("smite", "udeřit", "speciální útok / kouzlo", "He stole the dragon with smite.", "Sebral draka speciálním útokem."),
    ("respec", "přerozdělení", "změna rozložení schopností", "I respecced into defense.", "Přerozdělil jsem body do obrany."),
    ("hitbox", "zásahová zóna", "oblast, kam lze trefit postavu", "His hitbox is huge.", "Má obrovskou zásahovou zónu."),
    ("hitscan", "okamžitý zásah", "okamžitě zasahující zbraň", "Snipers are hitscan here.", "Sniperky tady trefí okamžitě."),
    ("aimbot", "mířicí robot", "podvodný program na míření", "He's using an aimbot.", "Používá podvodné automatické míření."),
    ("wallhack", "průhled zdí", "podvod vidící skrz zdi", "That kill looked like wallhack.", "To zabití vypadalo jako vidění skrz zdi."),
    ("cheater", "podvodník", "kdo používá podvody", "Report the cheater.", "Nahlas toho podvodníka."),
    ("hacker", "hacker", "hráč s podvodným softwarem", "There's a hacker in our lobby.", "V naší hře je podvodník."),
    ("speedrun", "rychloběh", "co nejrychlejší dohrání hry", "He set a speedrun record.", "Vytvořil rekord v nejrychlejším dohrání."),
    ("respawn camp", "kempení u spawnu", "číhání u místa oživení", "They're respawn camping us.", "Číhají na nás u místa oživení."),
    ("loadout", "výbava", "sestava zbraní a vybavení", "Pick a balanced loadout.", "Vyber vyváženou výbavu."),
    ("loot box", "krabice s kořistí", "balíček s náhodnou odměnou", "I opened a loot box.", "Otevřel jsem krabici s odměnou."),
    ("xp", "zkušenosti", "zkušenostní body", "This quest gives a lot of XP.", "Tenhle úkol dává hodně zkušeností."),
    ("level up", "zvýšit úroveň", "postoupit o úroveň", "I leveled up twice today.", "Dneska jsem postoupil o dvě úrovně."),
    ("endgame", "konec hry", "obsah pro nejvyšší úrovně", "The endgame is grindy.", "Konečný obsah je o dření."),
    ("speedrunner", "rychloběžec", "kdo hraje na nejrychlejší čas", "She's a known speedrunner.", "Je známá rychloběžkyně."),
    ("griefer", "škoditel", "kdo schválně kazí ostatním hru", "A griefer destroyed our base.", "Škoditel nám zničil základnu."),
    ("respawn timer", "časovač oživení", "odpočet do návratu do hry", "The respawn timer is too long.", "Čas do návratu je moc dlouhý."),
    ("hp", "životy", "body života", "I'm at low HP.", "Mám málo životů."),
    ("mana", "mana", "energie na kouzla", "I'm out of mana.", "Došla mi mana."),
    ("buff stack", "hromada vylepšení", "více posílení najednou", "Stack your buffs before the fight.", "Před bojem si nahromaď posílení."),
    ("kiting", "vlečení", "lákání nepřítele za pohybu", "Keep kiting the boss.", "Pořád toho bosse vodi za sebou."),
    ("proc", "spuštění", "náhodné spuštění efektu", "The fire damage just proc'd.", "Zrovna se spustilo ohnivé poškození."),
    ("respawn point", "bod oživení", "místo návratu do hry", "Set this as your respawn point.", "Nastav si tady bod oživení."),
    ("hitmarker", "značka zásahu", "indikátor zásahu soupeře", "I saw the hitmarker but no kill.", "Viděl jsem zásah, ale ne zabití."),
    ("headshot", "zásah do hlavy", "smrtelný zásah do hlavy", "Clean headshot!", "Čistý zásah do hlavy!"),
    ("respawn wave", "vlna oživení", "hromadné oživení týmu", "Wait for the respawn wave.", "Počkej na vlnu oživení."),
    ("nerf bat", "pálka oslabení", "tvrdé oslabení od vývojářů", "That hero got the nerf bat.", "Tenhle hrdina dostal pořádně naloženo."),
    ("hard carry", "tvrdé nesení", "naprosté táhnutí týmu", "He hard carried the match.", "Ten zápas dotáhl úplně sám."),
    ("solo queue", "samostatná fronta", "hra bez kamarádů, sám", "Solo queue is rough today.", "Hrát dneska sám je utrpení."),
    ("party", "parta", "skupina hráčů", "Join my party.", "Připoj se k mé partě."),
    ("lobby", "lobby", "místnost před hrou", "Wait in the lobby.", "Počkej v lobby."),
    ("matchmaking", "párování", "systém hledání soupeřů", "Matchmaking is slow tonight.", "Hledání hry je dneska pomalé."),
    ("ranked", "žebříčkový", "hodnocené zápasy", "Let's play ranked.", "Pojďme hrát hodnocené zápasy."),
    ("casual", "ležérní", "nehodnocená hra pro zábavu", "Just a casual match.", "Jen ležérní zápas pro zábavu."),
    ("respawn glitch", "chyba oživení", "závada při oživení", "There's a respawn glitch.", "Je tu chyba při oživování."),
    ("hitbox abuse", "zneužití zásahové zóny", "zneužívání chyb v zásazích", "That's hitbox abuse.", "To je zneužívání chyby v zásazích."),
    ("aim", "míření", "schopnost mířit", "Your aim is on point today.", "Tvoje míření je dneska přesné."),
    ("flick", "švihnutí", "rychlé otočení a zásah", "Sick flick shot!", "Šílený rychlý zásah!"),
    ("clip", "klip", "krátká herní nahrávka", "Did you save that clip?", "Uložil jsi ten klip?"),
    ("montage", "montáž", "sestřih nejlepších momentů", "He made a kill montage.", "Udělal sestřih zabití."),
    ("respawn kill", "zabití při oživení", "zabití hned po objevení", "I got a respawn kill.", "Dostali mě hned po oživení."),
    ("boss", "boss", "silný nepřítel na konci úrovně", "The final boss is brutal.", "Poslední boss je brutální."),
    ("speed boost", "zrychlení", "dočasné zvýšení rychlosti", "Grab the speed boost.", "Seber to zrychlení."),
    ("respawn lock", "zámek oživení", "blokované oživení", "We're under a respawn lock.", "Máme zablokované oživení."),
    ("hard reset", "tvrdý restart", "úplné resetování hry", "We needed a hard reset.", "Potřebovali jsme úplný restart."),
    ("ace", "eso", "vyřazení celého soupeřova týmu", "He got an ace!", "Vyřadil celý nepřátelský tým!"),
    ("wipe", "vyhlazení", "smrt celého týmu", "That fight was a full wipe.", "V tom boji padl celý tým."),
    ("aggro reset", "reset aggra", "ztráta pozornosti nepřátel", "The boss did an aggro reset.", "Boss ztratil cíl a otočil se."),
    ("respawn rush", "nával po oživení", "rychlý útok po návratu", "They respawn rushed us.", "Hned po oživení nás zaskočili."),
    ("hard stuck", "pevně zaseklý", "uvázlý na jedné úrovni žebříčku", "I'm hard stuck in gold.", "Trčím ve zlaté lize."),
    ("smurf account", "smurf účet", "vedlejší účet zkušeného hráče", "He plays on a smurf account.", "Hraje na vedlejším účtu."),
    ("respawn timer hack", "podvod na časovači oživení", "podvod zkracující oživení", "That looked like a respawn timer hack.", "Vypadalo to na podvod s časem oživení."),
    ("loot goblin", "kořistnický skřet", "hráč shánějící hlavně kořist", "He's a total loot goblin.", "Jde mu hlavně o kořist."),
    ("respawn beacon", "maják oživení", "předmět umožňující oživení", "Place a respawn beacon here.", "Polož sem maják oživení."),
    ("hard counter", "tvrdá protihra", "postava skvělá proti jiné", "This pick is a hard counter.", "Tahle volba ji úplně vyzraje."),
    ("speed cap", "strop rychlosti", "maximální rychlost", "You hit the speed cap.", "Narazil jsi na strop rychlosti."),
    ("respawn protection", "ochrana po oživení", "dočasná nezranitelnost", "You have respawn protection for two seconds.", "Po oživení jsi dvě vteřiny chráněný."),
    ("hard mode", "těžký režim", "obtížnější nastavení", "Try it on hard mode.", "Zkus to na těžký režim."),
    ("speedhack", "rychlostní podvod", "podvod na zrychlení pohybu", "That's a speedhack, report him.", "To je rychlostní podvod, nahlas ho."),
    ("respawn farm", "farmení oživení", "opakované zabíjení po oživení", "They set up a respawn farm.", "Začali nás kosit hned po oživení."),
    ("hard win", "těžká výhra", "vydřená výhra", "That was a hard win.", "To byla pořádně vydřená výhra."),
    ("clutch up", "sebrat se v klíči", "zachránit to v rozhodující chvíli", "Come on, clutch up!", "No tak, zachraň to!"),
    ("respawn loop", "smyčka oživení", "opakované rychlé umírání", "I'm stuck in a respawn loop.", "Zasekl jsem se ve smyčce umírání."),
    ("hard nerf", "tvrdé oslabení", "výrazné oslabení", "The class got a hard nerf.", "Ta třída dostala tvrdé oslabení."),
    ("speedrun strat", "rychloběžecká strategie", "trik pro nejrychlejší čas", "He used a new speedrun strat.", "Použil novou rychloběžeckou strategii."),
]
