# Gen Z slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

GEN_Z = [
    ("rizz", "rizz", "charisma, schopnost sbalit", "He's got serious rizz.", "Ten má fakt charisma na sbalení."),
    ("slay", "zabít", "exceloval/a, válíš", "You slayed that presentation!", "Tu prezentaci jsi totálně rozsekl/a!"),
    ("bussin", "praskající", "vynikající (hlavně jídlo)", "This pizza is bussin.", "Tahle pizza je naprosto skvělá."),
    ("cap", "čepice", "lež, kecy", "That's cap, I don't believe you.", "To jsou kecy, nevěřím ti."),
    ("no cap", "žádná čepice", "bez kecu, vážně", "This is the best, no cap.", "Tohle je nejlepší, bez kecu."),
    ("mid", "střední", "průměrný, nic moc", "The movie was mid.", "Ten film byl nic moc."),
    ("based", "založený", "stojí si za svým názorem", "That take is based.", "Tenhle názor je naprosto v pohodě, stojí si za ním."),
    ("cringe", "krčit se", "trapné, nepříjemné", "That video is so cringe.", "To video je hrozně trapné."),
    ("sus", "podezřelý", "podezřelý", "He's acting kinda sus.", "Chová se tak nějak podezřele."),
    ("bet", "sázka", "jasně, platí, dobře", "Wanna go? Bet.", "Jdeme? Jasně, platí."),
    ("fr", "fakt", "vážně, fakticky (for real)", "That's hard, fr.", "To je těžké, vážně."),
    ("ngl", "nelžu", "po pravdě (not gonna lie)", "Ngl, that was fun.", "Po pravdě, byla to zábava."),
    ("lowkey", "nízký klíč", "tak trochu, potajmu", "I lowkey love this song.", "Tak trochu tu písničku miluju."),
    ("highkey", "vysoký klíč", "naplno, otevřeně", "I highkey want pizza now.", "Naplno teď chci pizzu."),
    ("vibe", "vibrace", "atmosféra, nálada", "I love the vibe in here.", "Líbí se mi tu atmosféra."),
    ("vibe check", "kontrola vibrace", "test nálady/atmosféry", "Vibe check: how's everyone?", "Kontrola nálady: jak se všichni máte?"),
    ("flex", "ohnout", "chlubit se", "Stop flexing your new phone.", "Přestaň se chlubit novým mobilem."),
    ("ghosted", "duchem", "přestal/a se ozývat bez vysvětlení", "She ghosted me after one date.", "Po jednom rande se přestala ozývat."),
    ("salty", "slaný", "naštvaný, dotčený", "He's salty about losing.", "Je naštvaný, že prohrál."),
    ("shook", "otřesený", "v šoku, ohromený", "I was shook by the ending.", "Z toho konce jsem byl v šoku."),
    ("snatched", "popadnutý", "skvěle vypadající, perfektní", "Your outfit is snatched.", "Tvůj outfit je perfektní."),
    ("tea", "čaj", "drby, klepy", "Spill the tea!", "Vyklop ty drby!"),
    ("shade", "stín", "skrytá urážka, pohrdání", "She threw some shade at him.", "Pěkně si na něj rýpla."),
    ("stan", "stan", "velký fanoušek / fandit", "I stan that band.", "Toho kapelu zbožňuju."),
    ("ship", "loď", "fandit páru, přát si vztah", "I ship those two characters.", "Tyhle dvě postavy bych dal dohromady."),
    ("simp", "simp", "kdo se moc snaží o někoho", "Don't be a simp.", "Nebuď úplně zamilovaný blázen."),
    ("yeet", "yeet", "mrštit, hodit silou", "He yeeted the ball away.", "Zahodil ten míč hodně daleko."),
    ("bop", "rána", "skvělá písnička", "This track is a total bop.", "Tahle skladba je naprostá pecka."),
    ("glow up", "rozzářit nahoru", "výrazné zlepšení vzhledu", "She had a major glow up.", "Pořádně se vyšvihla."),
    ("main character", "hlavní postava", "být ve středu dění, žít naplno", "Today I feel like the main character.", "Dneska se cítím jako hlavní hrdina."),
    ("it's giving", "to dává", "vyzařuje to, působí to jako", "That outfit, it's giving summer.", "Ten outfit, působí to letně."),
    ("ate", "snědl", "skvěle to zvládl/a", "She ate and left no crumbs.", "Naprosto to rozsekla, bez chybičky."),
    ("understood the assignment", "pochopil zadání", "pochopil/a, co se čeká, a zvládl/a to", "She understood the assignment.", "Přesně věděla, co se čeká, a zvládla to."),
    ("delulu", "blouznivý", "naivně si něco namlouvat", "You're being a bit delulu.", "Trochu si něco namlouváš."),
    ("gyat", "gyat", "výraz úžasu/překvapení", "Gyat, that's huge!", "Ty jo, to je obrovské!"),
    ("mood", "nálada", "přesně tak se cítím", "Tired on Monday? Big mood.", "Unavený v pondělí? Přesně moje nálada."),
    ("lit", "rozsvícený", "skvělý, nabušený", "The party was lit.", "Ta party byla nabušená."),
    ("fire", "oheň", "super, perfektní", "Your new song is fire.", "Tvoje nová písnička je super."),
    ("goat", "koza", "nejlepší vůbec (greatest of all time)", "He's the GOAT of basketball.", "Je nejlepší basketbalista všech dob."),
    ("W", "W", "výhra, úspěch", "That's a W for the team.", "To je výhra pro tým."),
    ("L", "L", "prohra, neúspěch", "Taking an L today.", "Dneska beru prohru."),
    ("ratio", "poměr", "víc reakcí než lajků (kritika)", "Your comment got ratioed.", "Tvůj komentář pohořel v reakcích."),
    ("touch grass", "dotkni se trávy", "jdi ven, odpočiň od netu", "Bro, go touch grass.", "Kámo, běž ven mezi lidi."),
    ("npc", "NPC", "kdo se chová bez vlastního názoru", "He just repeats slogans like an NPC.", "Jen opakuje fráze jako figurka bez názoru."),
    ("ick", "ošklivost", "náhlá nechuť k někomu", "His laugh gave me the ick.", "Z jeho smíchu se mi udělalo nanic."),
    ("slaps", "plácá", "je to skvělé (o hudbě/jídle)", "This beat slaps.", "Tenhle beat je nářez."),
    ("vibing", "vibrující", "užívat si pohodu", "Just vibing at home.", "Jen tak v pohodě doma."),
    ("drip", "kapání", "stylové oblečení, styl", "Look at his drip.", "Koukni na jeho styl."),
    ("fit", "fit", "outfit, oblečení", "Nice fit today!", "Pěkný outfit dneska!"),
    ("clout", "vliv", "popularita, vliv online", "He did it just for clout.", "Udělal to jen kvůli popularitě."),
    ("hits different", "trefuje jinak", "působí to výjimečně", "This song hits different at night.", "Tahle písnička v noci působí úplně jinak."),
    ("living rent free", "bydlí zadarmo", "pořád na to myslíš", "That meme lives rent free in my head.", "Ten meme mi pořád straší v hlavě."),
    ("caught in 4k", "chycen ve 4K", "přistižen s jasným důkazem", "He got caught in 4k lying.", "Byl přistižen při lži s jasným důkazem."),
    ("its the for me", "to je pro mě to", "tohle je na tom (ne)nej", "The audacity, it's the lying for me.", "Ta drzost, hlavně to lhaní mi vadí."),
    ("rent free", "nájem zdarma", "nemůžeš na to přestat myslet", "She lives rent free in his mind.", "Pořád na ni musí myslet."),
    ("bestie", "nejlepšík", "kámoško, kámo", "Bestie, you won't believe this.", "Kámo, tomuhle neuvěříš."),
    ("slept on", "zaspaný", "podceňovaný", "This artist is so slept on.", "Tenhle umělec je hrozně podceňovaný."),
    ("gas", "plyn", "skvělé / přehnaná chvála", "Those shoes are gas.", "Ty boty jsou paráda."),
    ("hits", "zásahy", "to sedí, to je ono", "Cold water really hits in summer.", "Studená voda v létě fakt sedí."),
    ("cooked", "uvařený", "v háji, hotový", "I didn't study, I'm cooked.", "Neučil jsem se, jsem v háji."),
    ("clapped", "zatleskaný", "zničený, poražený", "We got clapped in that match.", "V tom zápase nás rozsekali."),
    ("opp", "protivník", "nepřítel, rival", "Watch out for the opps.", "Dej si pozor na protivníky."),
    ("bag", "taška", "balík peněz, výdělek", "He secured the bag.", "Pořádně si vydělal."),
    ("hardo", "tvrďák", "kdo se moc snaží být cool", "Don't be such a hardo.", "Nesnaž se být za každou cenu cool."),
    ("aura", "aura", "vyzařování, image", "He lost aura with that move.", "Tím tahem si dost pohoršil v očích ostatních."),
    ("yap", "kecat", "moc mluvit, žvanit", "Stop yapping and listen.", "Přestaň žvanit a poslouchej."),
    ("glaze", "polít glazurou", "přehnaně někoho vychvalovat", "Stop glazing that guy.", "Přestaň toho týpka tak vychvalovat."),
    ("menace", "hrozba", "rošťák, neřízená střela", "He's a menace to society.", "Je to neřízená střela."),
    ("savage", "divoký", "drsný, bezohledně super", "That comeback was savage.", "Ta odpověď byla pořádně drsná."),
    ("extra", "navíc", "přehnaný, dramatický", "She's being so extra today.", "Dneska to hrozně přehání."),
    ("basic", "základní", "tuctový, nezajímavý", "That's such a basic take.", "To je hrozně tuctový názor."),
    ("ghost", "duch", "zmizet bez rozloučení", "He's gonna ghost her, watch.", "Uvidíš, že jí prostě zmizí."),
    ("snack", "svačinka", "atraktivní osoba", "Wow, he's a whole snack.", "Páni, ten je fakt fešák."),
    ("pressed", "stlačený", "naštvaný, dotčený", "Why are you so pressed?", "Proč jsi tak naštvaný?"),
    ("hop off", "seskoč", "odpal, nech mě být", "Hop off, I didn't ask.", "Nech mě být, neptal jsem se."),
    ("valid", "platný", "v pořádku, oprávněné", "Your feelings are valid.", "Tvoje pocity jsou oprávněné."),
    ("iconic", "ikonický", "nezapomenutelný, skvělý", "That moment was iconic.", "Ten moment byl naprosto kultovní."),
    ("periodt", "tečka", "a tečka, konec diskuze", "I'm right, periodt.", "Mám pravdu a tečka."),
    ("say less", "řekni méně", "rozumím, není třeba víc", "Pizza tonight? Say less.", "Dneska pizza? Není třeba víc říkat."),
    ("fam", "rodina", "kámo, partičko", "What's good, fam?", "Co je, kámo?"),
    ("lowkey obsessed", "nízký klíč posedlý", "tak trochu závislý/zamilovaný", "I'm lowkey obsessed with this show.", "Ten seriál mě tak trochu pohltil."),
    ("on god", "na boha", "přísahám, fakt", "On god, I'll be there.", "Přísahám, že tam budu."),
    ("vibes only", "jen vibrace", "jen pohoda, žádný stres", "Weekend, good vibes only.", "Víkend, jen samá pohoda."),
    ("simp energy", "simp energie", "přehnaná snaha o někoho", "That text gave simp energy.", "Ta zpráva působila až moc zamilovaně."),
    ("ate that up", "snědl to", "zvládl to na výbornou", "She ate that performance up.", "To vystoupení naprosto rozsekla."),
    ("not me doing", "ne já dělající", "(ironicky) to si dělám fakt já", "Not me crying at a commercial.", "To fakt brečím u reklamy."),
    ("the audacity", "ta drzost", "ta drzost", "The audacity of him to ask!", "Ta drzost, že se vůbec zeptal!"),
    ("zesty", "kořeněný", "výrazný, energický (často hravě)", "That dance was zesty.", "Ten tanec byl pořádně výrazný."),
    ("goated", "kozovaný", "naprosto nejlepší", "This game is goated.", "Tahle hra je naprostá špička."),
    ("npc behavior", "chování NPC", "stádní, bezmyšlenkovité chování", "Following trends blindly is npc behavior.", "Slepě následovat trendy je chování bez vlastního názoru."),
    ("ratio'd", "vypoměrovaný", "převálcovaný v reakcích", "His tweet got ratio'd hard.", "Jeho tweet pořádně pohořel."),
    ("clutch", "spojka", "v klíčový moment skvělý", "That save was clutch.", "Ten zákrok přišel v klíčový moment."),
    ("vibe killer", "zabiják nálady", "kdo kazí atmosféru", "Don't be a vibe killer.", "Nekaz tu atmosféru."),
    ("hot take", "horký názor", "kontroverzní názor", "Hot take: pineapple pizza is great.", "Kontroverzní názor: pizza s ananasem je super."),
    ("real one", "skutečný", "věrný kamarád", "Thanks, you're a real one.", "Díky, jsi opravdový kámoš."),
    ("low effort", "nízké úsilí", "odfláknuté, bez snahy", "That meme is low effort.", "Ten meme je odfláknutý."),
    ("flop", "žbluňk", "propadák, neúspěch", "The launch was a flop.", "To uvedení byl propadák."),
    ("snapped", "praskl", "podal extra skvělý výkon", "She really snapped on that verse.", "V tý sloce to fakt rozsekla."),
    ("its over", "je konec", "(dramaticky) je po všem", "No coffee left? It's over.", "Došla káva? Tak to je konec."),
    ("crash out", "zhroutit ven", "totálně se sesypat, přepálit reakci", "He's about to crash out over this.", "Kvůli tomuhle se snad úplně sesype."),
]
