# Workplace slang with literal Czech, real meaning, examples.
# (english, literalCzech, actualMeaningCzech, exampleEn, exampleCz)

WORKPLACE = [
    ("deadline", "mrtvá čára", "termín odevzdání", "The deadline is on Friday.", "Termín je v pátek."),
    ("overtime", "přesčas", "práce přesčas", "I worked overtime all week.", "Celý týden jsem dělal přesčasy."),
    ("micromanage", "mikrořídit", "úzkostlivě řídit každý detail", "My boss micromanages everything.", "Šéf řídí úplně každý detail."),
    ("burnout", "vyhoření", "vyčerpání z přepracování", "I'm close to burnout.", "Jsem na pokraji vyhoření."),
    ("nine to five", "devět až pět", "běžná kancelářská práce", "I'm tired of the nine to five.", "Už mě nebaví ta kancelářská rutina."),
    ("call in sick", "zavolat nemocný", "omluvit se kvůli nemoci", "I had to call in sick.", "Musel jsem se omluvit kvůli nemoci."),
    ("clock in", "napíchnout dovnitř", "zaznamenat příchod do práce", "I clock in at eight.", "Píchám příchod v osm."),
    ("clock out", "napíchnout ven", "zaznamenat odchod z práce", "She clocked out early.", "Odešla z práce dřív."),
    ("raise", "zvednutí", "zvýšení platu", "He asked for a raise.", "Požádal o zvýšení platu."),
    ("promotion", "povýšení", "postup na vyšší pozici", "She got a promotion.", "Dostala povýšení."),
    ("the boss", "šéf", "nadřízený", "The boss wants to see you.", "Šéf tě chce vidět."),
    ("colleague", "kolega", "spolupracovník", "My colleague helped me.", "Kolega mi pomohl."),
    ("team player", "týmový hráč", "kdo umí spolupracovat", "We need a real team player.", "Potřebujeme opravdového týmového hráče."),
    ("brainstorm", "bouře mozku", "společné vymýšlení nápadů", "Let's brainstorm some ideas.", "Pojďme vymyslet nějaké nápady."),
    ("touch base", "dotknout se mety", "krátce se spojit a probrat", "Let's touch base on Monday.", "V pondělí to krátce probereme."),
    ("circle back", "obkroužit zpět", "vrátit se k tématu později", "Let's circle back on this later.", "K tomuhle se vrátíme později."),
    ("on the same page", "na stejné stránce", "mít stejné info/názor", "Are we all on the same page?", "Rozumíme si všichni stejně?"),
    ("low-hanging fruit", "nízko visící ovoce", "snadno dosažitelný cíl", "Let's start with low-hanging fruit.", "Začněme tím, co je snadné."),
    ("move the needle", "pohnout ručičkou", "dosáhnout výrazného posunu", "This won't move the needle.", "Tohle s tím nehne."),
    ("ping me", "pingni mě", "napiš/ozvi se mi", "Ping me when it's ready.", "Ozvi se, až to bude hotové."),
    ("loop in", "zacyklit dovnitř", "zahrnout do komunikace", "Loop me in on that email.", "Přidej mě do té komunikace."),
    ("out of the loop", "mimo smyčku", "nemít aktuální info", "Sorry, I'm out of the loop.", "Promiň, nemám aktuální informace."),
    ("eod", "konec dne", "do konce pracovního dne", "Send it by EOD.", "Pošli to do konce dne."),
    ("eow", "konec týdne", "do konce týdne", "I'll finish it by EOW.", "Dodělám to do konce týdne."),
    ("asap", "co nejdřív", "co nejdříve", "We need this ASAP.", "Potřebujeme to co nejdřív."),
    ("fyi", "pro tvou informaci", "pro tvou informaci", "FYI, the client called.", "Pro info, volal klient."),
    ("eta", "odhadovaný čas", "odhadovaná doba dokončení", "What's the ETA on the report?", "Kdy odhadem bude report?"),
    ("kpi", "klíčový ukazatel", "měřítko výkonu", "We missed our KPIs.", "Nesplnili jsme cíle výkonu."),
    ("synergy", "synergie", "součinnost, vzájemný přínos", "We're looking for synergy.", "Hledáme vzájemný přínos."),
    ("bandwidth", "šířka pásma", "kapacita na další práci", "I don't have the bandwidth.", "Nemám na to kapacitu."),
    ("deliverable", "dodávka", "výstup k odevzdání", "What are the deliverables?", "Jaké jsou výstupy?"),
    ("action item", "akční položka", "úkol k vyřízení", "Let's list the action items.", "Sepišme si úkoly."),
    ("follow up", "navázat", "připomenout, navázat", "I'll follow up tomorrow.", "Zítra to připomenu."),
    ("heads-up", "hlavy nahoru", "upozornění předem", "Thanks for the heads-up.", "Díky za včasné upozornění."),
    ("workaround", "obejití", "náhradní řešení", "We found a workaround.", "Našli jsme náhradní řešení."),
    ("ramp up", "rozjet nahoru", "postupně zvyšovat", "We need to ramp up production.", "Musíme rozjet výrobu."),
    ("onboarding", "naloďování", "zaškolení nového člověka", "Her onboarding starts Monday.", "Její zaškolení začíná v pondělí."),
    ("offboarding", "vyloďování", "ukončení pracovního poměru", "We handled his offboarding.", "Zařídili jsme jeho odchod."),
    ("red tape", "červená páska", "byrokracie", "There's too much red tape.", "Je v tom moc byrokracie."),
    ("paper trail", "papírová stopa", "doložitelná dokumentace", "Keep a paper trail.", "Měj o tom záznamy."),
    ("micromanager", "mikromanažer", "kdo řídí každý detail", "Nobody likes a micromanager.", "Nikdo nemá rád šéfa, co řeší každý detail."),
    ("yes man", "ano muž", "kdo vždy souhlasí s šéfem", "He's just a yes man.", "Jen šéfovi přitakává."),
    ("team building", "budování týmu", "stmelovací akce", "We have team building Friday.", "V pátek máme teambuilding."),
    ("water cooler talk", "řeči u chladiče", "neformální klábosení v práci", "It's just water cooler talk.", "Jsou to jen kancelářské řeči."),
    ("desk jockey", "stolní žokej", "kdo celý den sedí u stolu", "I'm a desk jockey these days.", "Teď jen sedím u stolu."),
    ("crunch time", "křupavý čas", "vypjaté období před termínem", "It's crunch time before launch.", "Před spuštěním je krizový čas."),
    ("pull an all-nighter", "tahat celonočku", "pracovat celou noc", "I pulled an all-nighter.", "Probděl jsem celou noc nad prací."),
    ("the grind", "dření", "každodenní pracovní dřina", "Back to the grind on Monday.", "V pondělí zpátky do kolotoče."),
    ("dead weight", "mrtvá váha", "neužitečný člen týmu", "He's just dead weight.", "Je jen na obtíž."),
    ("rockstar", "rocková hvězda", "skvělý, výkonný pracovník", "She's a rockstar on our team.", "V týmu je naprostá hvězda."),
    ("go-getter", "získávač", "ambiciózní, iniciativní člověk", "We need a go-getter.", "Potřebujeme někoho s tahem na branku."),
    ("brown-noser", "hnědonosý", "patolízal, vlezdoprdelka", "He's such a brown-noser.", "Je to hroznej patolízal."),
    ("throw under the bus", "hodit pod autobus", "hodit vinu na kolegu", "He threw me under the bus.", "Hodil to na mě."),
    ("take the fall", "vzít pád", "vzít vinu na sebe", "She took the fall for the team.", "Vzala vinu za tým na sebe."),
    ("step up", "vykročit nahoru", "ujmout se, zabrat", "We need you to step up.", "Potřebujeme, abys to vzal na sebe."),
    ("step down", "vykročit dolů", "odstoupit z funkce", "The manager stepped down.", "Manažer odstoupil."),
    ("up to speed", "na rychlost", "v obraze, zorientovaný", "Get me up to speed.", "Uveď mě do obrazu."),
    ("game plan", "herní plán", "plán postupu", "What's our game plan?", "Jaký máme plán?"),
    ("ballpark", "hřiště", "hrubý odhad", "Give me a ballpark number.", "Řekni mi hrubý odhad."),
    ("deep dive", "hluboký ponor", "důkladný rozbor", "Let's do a deep dive on data.", "Pojďme si data pořádně rozebrat."),
    ("quick win", "rychlá výhra", "snadný rychlý úspěch", "Let's grab a quick win.", "Pojďme pro snadný rychlý úspěch."),
    ("blocker", "blokátor", "překážka v postupu", "What's the blocker here?", "Co tu brání postupu?"),
    ("escalate", "eskalovat", "předat výš k řešení", "We had to escalate the issue.", "Museli jsme problém předat výš."),
    ("stakeholder", "držitel podílu", "zainteresovaná strana", "Update the stakeholders.", "Informuj zainteresované strany."),
    ("alignment", "zarovnání", "shoda na směru", "We need better alignment.", "Potřebujeme se víc sladit."),
    ("offline", "mimo linku", "probrat soukromě/později", "Let's take this offline.", "Tohle probereme zvlášť."),
    ("circle of trust", "kruh důvěry", "okruh zasvěcených", "She's in the circle of trust.", "Patří mezi zasvěcené."),
    ("face time", "čas tváří", "osobní viditelnost u vedení", "He wants face time with the CEO.", "Chce být víc vidět u šéfa."),
    ("hot desk", "horký stůl", "sdílené nestálé místo", "We use hot desks now.", "Teď máme sdílené stoly."),
    ("open door policy", "politika otevřených dveří", "vstřícnost nadřízeného", "My manager has an open door policy.", "Můj manažer je vždy k dispozici."),
    ("dress code", "oděvní kód", "pravidla oblékání", "What's the office dress code?", "Jaký je v kanceláři dress code?"),
    ("casual friday", "neformální pátek", "volnější oblékání v pátek", "It's casual Friday today.", "Dneska je neformální pátek."),
    ("water under the bridge", "voda pod mostem", "vyřešená minulost", "That mistake is water under the bridge.", "Ta chyba je dávno za námi."),
    ("pushback", "tlak zpět", "odpor, námitky", "We got pushback from the team.", "Tým měl námitky."),
    ("buy-in", "nákup do", "podpora, souhlas zainteresovaných", "We need management buy-in.", "Potřebujeme podporu vedení."),
    ("low morale", "nízká morálka", "špatná nálada v týmu", "Morale is low after layoffs.", "Po propouštění je špatná nálada."),
    ("layoff", "propuštění", "hromadné propouštění", "There were layoffs last month.", "Minulý měsíc propouštěli."),
    ("severance", "odstupné", "odstupné při propuštění", "He got a severance package.", "Dostal odstupné."),
    ("notice period", "výpovědní lhůta", "doba po výpovědi", "My notice period is two months.", "Mám dvouměsíční výpovědní lhůtu."),
    ("hand in notice", "podat výpověď", "dát výpověď", "She handed in her notice.", "Podala výpověď."),
    ("probation", "zkušební doba", "zkušební období", "I'm still on probation.", "Jsem ještě ve zkušebce."),
    ("perks", "vychytávky", "zaměstnanecké benefity", "The job has great perks.", "Ta práce má skvělé benefity."),
    ("remote", "vzdálený", "práce na dálku", "I work remote now.", "Teď pracuju na dálku."),
    ("hybrid", "hybridní", "kombinace kanceláře a domova", "We have a hybrid setup.", "Máme hybridní režim."),
    ("standup", "postojka", "krátká denní porada", "Daily standup is at nine.", "Krátká porada je v devět."),
    ("sync", "synchronizace", "krátká schůzka k sladění", "Let's have a quick sync.", "Dáme si krátkou schůzku k sladění."),
    ("one-on-one", "jeden na jednoho", "osobní schůzka s nadřízeným", "I have a one-on-one with my boss.", "Mám osobní schůzku se šéfem."),
    ("debrief", "rozbor po akci", "shrnutí po dokončení", "Let's debrief after the launch.", "Po spuštění to vyhodnotíme."),
    ("offsite", "mimo pracoviště", "akce mimo kancelář", "We have a team offsite.", "Máme týmovou akci mimo kancelář."),
    ("crunch", "křupnutí", "nárazové přetížení prací", "We're in crunch this week.", "Tenhle týden makáme na doraz."),
    ("backlog", "nahromaděné", "fronta nevyřízených úkolů", "The backlog is huge.", "Máme obrovskou frontu úkolů."),
    ("sprint", "spurt", "krátký pracovní cyklus", "This sprint ends Friday.", "Tenhle sprint končí v pátek."),
    ("retro", "ohlédnutí", "schůzka k vyhodnocení sprintu", "We discussed it in retro.", "Probrali jsme to na retru."),
    ("scope creep", "rozlézání rozsahu", "nekontrolované rozšiřování zadání", "Watch out for scope creep.", "Pozor na rozlézání zadání."),
    ("blocker meeting", "schůzka o překážkách", "porada k odstranění překážek", "We need a blocker meeting.", "Potřebujeme poradu o překážkách."),
    ("face the music", "čelit hudbě", "nést následky v práci", "He had to face the music for the error.", "Za tu chybu musel nést následky."),
    ("burn the candle at both ends", "pálit svíčku z obou konců", "vyčerpávat se prací i jinde", "She's burning the candle at both ends.", "Vyčerpává se ze všech stran."),
    ("hit the ground running", "běžet hned po dopadu", "rozjet se hned naplno", "She hit the ground running on day one.", "Hned první den se zapojila naplno."),
    ("learning curve", "křivka učení", "náročnost zaučení", "There's a steep learning curve.", "Zaučení je dost náročné."),
    ("dead-end job", "slepá práce", "práce bez perspektivy", "It's a dead-end job.", "Je to práce bez budoucnosti."),
]
